### ISSUE TITLE
Add sorting to Reference

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#129]
Add sorting to the Reference class:
- [ ] Parse sort from URI, also implement multiple sort columns.
- [ ] On read(): 
* If sort is available, use that. Append missing key columns.
* If sort is not available, used row_order from table-display annotation. Append missing key columns.
* Otherwise, no sorting
- [ ] When sorting is changed, a new sortReference(sort) method that makes a new Reference with the new sort.

**Comment by robes** [comment]
I'm glad you went this way with it. I got thinking about it yesterday night and felt like this would be the right way too.

I would suggest a change to the interface, instead of `sortReference(sort)`, just name it `sort(ordering)` where `ordering` is an object like this `{ 'column-name': ` either `'asc'` or `'dsc'` `...}`.

Usage will be like:
```
var sortedref = ref.sort( { 'title': 'asc', 'gene': 'dsc', 'id': 'asc' } );
```

And this leads to a separate but related issue that I believe we will need to expose the `uri` from the reference in a way that the client can use it. Because I would anticipate that an application like 'recordset' will make a `sort(...)` call like above and then it will need to get the URI from the refernece in order to display in the permalink. I have thought about this but won't document here.

**Comment by shinyichen** [comment]
I wrote something similar, except input param is in the same format as in the schema annotation for table-display.row_order. `{"column":colname, "descending":true}...]`

**Comment by karlcz** [comment]
The sort needs to be an ordered list of per-column sort instructions
(column name and ascending or descending).

An object/mapping has no ordering.

**Comment by robes** [comment]
Ugh... @karlcz thanks, I keep forgetting about js object keys aren't ordered...

So yes, we should keep with the way Jennifer has it specified.

But I still prefer the shorter function name `sort(...)`. That's a superficial detail though.
