### ISSUE TITLE
Support 2016 Table Alternatives

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#170]
This is needed to allow a view to be displayed in recordset, but when clicking on an individual record, it should lead to a record in an actual table. 

We could extend contextualize to take this annotation into account and set the Reference.uri correctly. @robes thoughts?

**Comment by robes** [comment]
Yes, but...

How does one tell the difference between a 'base entity storage table' and a table that abstracts it? I think things are getting messy with all of these annotations and we are missing some core concepts to simplify our data services.

**Comment by hongsudt** [comment]
From chaise perspective, there is no difference, except through the annotation. And Views seems to be what data modelers use to work-around frontend limitation.  

If there is a way to aggregate selected related tables into the compact view of the main entity, maybe this will reduce the use of view?

**Comment by karlcz** [comment]
I think this was one of the first drafts introducing the 'context'
concept and it looks a little rough because of it.

We could also turn it around and make the annotation on the base
storage table to list which abstracted view to prefer for each
context.  This would probably be easier to maintain as a DBA and less
chance for ambiguity.  We could also use the same name-pairs notation
we use for constraints now:


```
table.annotations['tag:isrd.isi.edu,2016:table-alternatives'] = {
  context1: [ "Schema1", "View1" ],
  context2: [ "Schema1", "VIew2" ],
  ...
};
```

We'd still declare the same model requirements: the alternative table
or view should have a (psuedo) primary key that is a foreign key to
the base storage table.  The base storage table is the one bearing
this annotation.

**Comment by hongsudt** [comment]
What about this strategy?

* Create a Table._baseTable. If it is undefined, the baseTable is the same as the table itself.

* Modify Tuple to support
  - Add Tuple.getReference() which returns an uncontextualized reference to get to the tuple.
  - override the above reference.read() to use the original tuple._data instead of going to the server to get the same data.
  
* Modify contextualize to take into account the alternative table and base table.
  - get the baseTable
  - add a getter to retrieve alternative table (._alternativeTable) for each context using the baseTable. Only the base tables should have this annotation!
  - if alternativeTable is defined, create a contextualize reference to the alternativeTable. Otherwise, the contextualization is done at the same reference.

* To support the app_links, add Reference.appLocation object 

From recordset:
```
resolve -> Reference (R0)
  - R0.contextualize.compact -> Reference (R1)
    - R1.read -> Page (P0)
      - For each P0.tuple (T)
        - T.getReference (R2)
          - R2.contextualize.detail -> Reference (R3)
	  - R3 should contain information needed to navigate to the right app and table
```
RBK example: image is the base table, and v_image is a view that is used to show resultset
* case1: `chaise/recordset/#1/rbk:image`
  - `R0.table=image, R1.table=v_image, R2.table=image, R3.table=image` 
* case2: `chaise/recordset/#1/rbk:v_image`
  - `R0.table=v_image, R1.table=v_image, R2.table=image, R3.table=image`

Note: Both cases should have exactly the same content which is what's in v_image, unless we want to extend the app to ignore contextualize.

From record2:
```
resolve -> Reference (R0)
  - R0.contextualize.compact -> Reference (R1)
    - R1.read -> Page (P0)
    - R1.related[] -> Reference[]
      - R1.related[i].contextualize.detail -> Reference (R2)
        - R2 should contain information needed to navigate to the right app and table
```

**Comment by shinyichen** [comment]
Alternative table's `Reference` should be created using the URI of the alternative table, keeping the same filters and modifiers of the base table's `Reference`. To transpose the filter, we need to find mapping columns. It's possible base table has multiple primary keys. Does the alternative table have all the columns of all the primary keys of the base table (vs. just one set of key)?

**Comment by karlcz** [comment]
I don't think you can assume a mapping from base table columns to alternative table columns except for the key which MUST be a non-NULL key in the alternative key table w/ a foreign key constraint mapping it to a key in the base table. Therefore, you can introspect on the "primary key which is a foreign-key to base table" to find the mapping w/o any assumptions about column naming.

In my opinion, you should not try to map filters between tables but just add another join to the ermrest query, e.g.

    /entity/Base/col=val.../(kcol1)=(Alternative:kcol2)

The same holds if going in the reverse direction. An alternative could quite likely contain columns that have no equivalent in the base table and so filters cannot be relocated from one table to the other, but the join will work:

    /entity/Alternative/col=val.../(kcol2)=(Base:kcol1)

**Comment by karlcz** [comment]
To be more specific:

1. I think that all alternatives should be required to use the **same** key from the base table, so the entire clique of alternative tuples representing a single entity all contain the same key value, whether or not base table has any other keys. This would allow direct conversion from one context to another for references to the same entity.
2. Recontextualizing an unfiltered reference should be able to swap out the table without a join.
3. Recontextualizing a single-entity reference should be able to swap out the table and translate the key filter constraint since they share the same value and just need a column renaming.
4. General filters, if supported, would require the joined form for recontextualization. This introduces ugly UX problems i.e. how to present to the user the influence of these joined filters.

There is one more special case in our app flow that I don't think is covered elegantly by the above: the result of a multi-insert action on the `recordedit` app needs to flow to `recordset` while setting a disjunctive filter on the key. If `recordset` needs to recontextualize during initialization to show these results, it would either produce the ugly joined form or have to think harder and determine that the filters only involve the key material and can be translated in spite of being more complex than a simple single-entity reference.

**Comment by shinyichen** [comment]
- [ ] When contextualizing a `reference`, if `._table._baseTable` is not `._table` (this is an alternative table), use the base table to get the alternative table of that context.
