### ISSUE TITLE
markdown handler for drop-down list 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#172]

**Comment by chiragsanghvi** [comment]
@hongsudt @karlcz Does this format works for dropdown list ?

```js

/*
 * Format "::: dropdown DROPDOWN_TITLE{.btn-success} [CAPTION](LINK){ATTR=VALUE .CLASSNAME}  [CAPTION](LINK){ATTR=VALUE .CLASSNAME} \n:::"
 * String inside '{}' is Optional, specifies attributes to be applied to prev element
 */

::: dropdown DROPDOWNCAPTION{.btn-lg} [CAPTION1](https://dev.isrd.isi.edu/chaise/search){.btn .btn-danger} [CAPTION2](https://dev.isrd.isi.edu/chaise/search) [CAPTION3](https://dev.isrd.isi.edu/chaise/search) \n:::


```
**OUTPUT**
```html
<p>
	<div class="btn-group markdown-dropdown">
		<button type="button"  class="btn btn-primary btn-lg">MYCAPTION</button>
		<button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  class="btn btn-primary dropdown-toggle btn-lg">
			<span class="caret"></span>
			<span class="sr-only">Toggle Dropdown</span>
		</button>
		<ul class="dropdown-menu">
			<li>
				<a href="https://dev.isrd.isi.edu/chaise/search" class="btn btn-danger" >CAPTION1</a>
			</li>
			<br>
			<li>
				<a href="https://dev.isrd.isi.edu/chaise/search" >CAPTION2</a>
			</li>
			<br>
			<li>
				<a href="https://dev.isrd.isi.edu/chaise/search" >CAPTION3</a>
			</li>
		</ul>
	</div>
</p>
```
You can test it [here](https://tonicdev.com/chiragsanghvi/57c6118b039c761400dd18fa) for a combination of iframe and dropdown syntax.

**Comment by chiragsanghvi** [comment]
The output is in the Bootstrap [dropdown button](http://getbootstrap.com/components/#btn-dropdowns-split) format.

**Comment by hongsudt** [comment]
The format looks fine to me.. Just have a few questions: 
* Is `\n` required prior to the ending `:::`? 
* It seems like space is used to separate between each dropdown element. If I add `\n` between each dropdown element, will this be ok as well?

**Comment by chiragsanghvi** [comment]
* Is `\n` required prior to the ending `:::`? 

Yes, because the container plugin will not be able to determine the ending of the tag. This syntax strictly cannot be changed.

* It seems like space is used to separate between each dropdown element. If I add `\n` between each dropdown element, will this be ok as well? 

The container plugin reads the content defined after the  `::: dropdown ` string. So if you specify a \n, that content won't be passed to my parser and will be parse as default markdown. Hence, there should be no \n prior the actual end of the tag.
