### ISSUE TITLE
URL Parser

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#196]
Investigate js parser to parse the app url.

@robes @karlcz I am assuming that we can start with ermrest grammar? Does that make sense?

**Comment by hongsudt** [comment]
@RFSH can you send the pointers to the javascript parsers that you were looking at before?

**Comment by RFSH** [comment]
In [here](https://sap.github.io/chevrotain/performance/) you can see a performance comparision of Javascript parsing libraries. Since we want to just parse one line at a time, performance is not that important for us; but we can use this link as a reference to several Javascript parsing libraries.

[PEG.js](https://github.com/pegjs/pegjs) looks like a good candidate; based on popularity (number of stars), maintainability, and ease of use.

**Comment by hongsudt** [comment]
This issue should addess informatics-isi-edu/chaise#693.

**Comment by RFSH** [comment]
Since we created this issue our parser has evolved a lot. It's still doing string matching instead of actual parsing, but it's more complicated and with the addition of faces it can handle complicated paths. I don't think changing it to an actual parser is feasible anymore. I am going to close this issue.
