### ISSUE TITLE
expose response object in promise

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#231]
Currently, only the payload is exposed. In addition to the content, we need to expose the status code, headers, etc.

**Comment by shinyichen** [comment]
How about returning the http response object? And for Reference.resolve(), create an http response object. (is that possible?)

Including @jrchudy in the discussion

**Comment by jrchudy** [comment]
I believe that is the norm, to return the full http response object. All of our requests that interact with ERMRest should return that. 

Resolve doesn't need to be changed because we aren't fetching any data from the database, just the _schema_ and _metadata_ information. Chase only needs the data from the response object. Dealing with the headers should be done in ermrestJS.

**Comment by karlcz** [comment]
Eventually, something needs to track the ETag returned with the model and decide that the app has gotten out of sync with the server.

1. App bootstraps and gets catalog model+etag
2. App uses one or more ermrestjs APIs
3. App encounters a 409 Conflict
  - Could be due to user error
  - Could be due to model inconsistency
4. *something* refetches model and compares old/new etag
  - identical etags mean original model is still current
  - different etags mean app has gotten out of sync

I think we've declared that this would be treated as a fatal error for the current apps, so they would just throw an alert modal with an option to restart the app.

**Comment by robes** [comment]
Just to recap quick in-person chat with @jrchudy and @shinyichen, we think this should be handled internal to ermrestjs and does _not_ need to be exposed by ermrestjs through the reference.resolve api.

But we ought to review the various error modes as @karlcz points out above and determine whether anything more does need to be exposed to the client.

**Comment by hongsudt** [comment]
It seems like this issue is already resolved.
