### ISSUE TITLE
supporting non-lexical sorting (e.g. allow sorting to be done based on a different columns)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#275]
For example, in RBK and Facebase, there is a column called `age stage` that has values like `3.5 weeks, 10 weeks, etc.` When this column is sorted, it needs to be sorted based on their ordinal ranking e.g. 3.5 comes before 10 weeks. 

@karlcz @robes should we add an annotation to specify the mapping columns to be used for sorting? 

Another related issue.. since each column can be annotated with a markdown.. How do we deal with sorting for those columns. Pesudo-columns have the same issue..

**Comment by karlcz** [comment]
We already have a row_order annotation which could be applied on a domain table.  So maybe what you're asking for is a heuristic to assume that sorting by foreign keys should actually sort by the row_order of the referenced domain table instead of the actual foreign key value?

You would need to form a joined entity path and include the other column in the projection so that you can ask for sort based on that column.  I.e. if your age stage column is a foreign key to an age-stage domain table which includes a ranking column, you need to include this domain table in the join and project the ranking column and mention the ranking column in the sort modifier.

ERMrest only allows sorting by **output** columns in the projection.

**Comment by karlcz** [comment]
After further discussion, I agree that the case with markdown_pattern creates a problem. We cannot realistically determine a semantic sort order for columns where the presentation has been remapped by an arbitrary markdown_pattern expansion.

So, we probably need an annotation to suggest a "column_order" using the same array of sort keys as in the "row_order" annotation option.  With this, the app could apply sort when the user requests sorting on a column. Without this, the app should probably disable sorting on columns that have been transformed by markdown_pattern expansion.

For psuedo columns, I think we could inherit the row_order from the linked domain table instead. We might also allow the column_order annotation on a foreign key in order to explicitly override the generic domain table row_order?

**Comment by karlcz** [comment]
I pushed [column_order annotation options](https://github.com/informatics-isi-edu/ermrest/commit/171f81912ce463e408f305361f4724bfe9d0bba9?short_path=cf73c73#diff-cf73c73d214853f687df4473ad3e234a)
