### ISSUE TITLE
handle column displayname correctly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#285]
The column displayname can be set through the `tag:misd.isi.edu,2015:display` annotation, which has the following syntax: 
```
    {... "name": name ...}: The name to use in place of the model element's original name.
    {... "name_style": { "underline_space": uspace , "title_case": tcase } ...}: Element name conversion instructions.
```

- [x] escape the column display name derived from the "name" property in the display annotation or other base column names.
- [ ] `{"markdown_name"`: markdown}` provides explicit markdown string.
- [ ] `{"name_style": { `"markdown"`: true }}` means to interpret the effective name string as Markdown for presentation purposes. A value of `false` means to present it verbatim (i.e. with proper escaping). This option is inherited like the other name-style options.

**Comment by robes** [comment]
To keep things simple, we could just say that the `name` attribute may include markdown. So we alway render it with the markdown engine if the `name` annotation is given.

When the `name` annotation is not given, then we escape the column name. I.e., column.displayname = escaped column.name, in the default case where not `name` annotation is given.

**Comment by hongsudt** [comment]
For simplicity, I think we need to distinguish whether it is a markdown column or just a static replacement of the column.. I think the two cases require different escape mechanism.

**Comment by hongsudt** [comment]
@karlcz @robes @RFSH it seems like we already have this issue open.. Please modify the detail here.

**Comment by robes** [comment]
We can replace the `name_markdown` in the original description with something like `render_markdown` as a `true`/`false` flag.

**Comment by karlcz** [comment]
I am proposing something a little more complex, because I think it gives a saner model.

1. the existing `name` field remains as is for verbatim content that will be escaped for presentation
2. a new `markdown_name` field allows an explicit markdown string with no ambiguity
3. a new `name_style`-> `markdown` flag allows markdown rendering to be toggled. I've specified it to only apply to actual model names to be consistent with the other name-style options.

The bare `markdown_name` allows for very sparse overrides of a model, i.e. a custom string here or there without any systematic conversion to markdown.  You can override just a table name, for example, while still using default non-markdown column names from the model.

The `name_style`->`markdown` flag, like the title-case and underline-space options, will only apply for systematic conversion of model element names and follows the same inheritence model.

**Comment by karlcz** [comment]
I will wait for next standup to reach closure before I push these changes to the ermrest user-doc stuff...

**Comment by hongsudt** [comment]
This issue is pending on @howdyjessie's PR on using the isHTML to render the column names as html. I think the ermrestjs part is done.

**Comment by howdyjessie** [comment]
I just merged the displayname PR for Chaise.
