### ISSUE TITLE
Add "primary key" flag

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#34]
From the discussion started in [chaise#338](https://github.com/informatics-isi-edu/chaise/issues/338#issuecomment-219779327): 
"It would be nice to have some sort of "primary key"-esque flag in ermrestjs so that we don't duplicate the code to find this shortest key in multiple Chaise apps. Maybe it could be something along the lines of `table.[uniqueId | uniqueKey].get()`. If not, we could also abstract it away to the `common/` folder, but it feels strange to put this kind of key-finding operation in Chaise."

Tagging @robes to get his take on whether this is a good idea.

**Comment by robes** [comment]
I am in favor of the idea. @karlcz maybe this can be solved by a simple heuristic:
- if a table has only one simple key, it must be the `primarykey`
- if a table has more than one simple key, then pick the first one and declare it the `primarykey`
- we could add an annotation `tag:...:primarykey` to ermest's recommendations to override this behavior

Then as @howdyjessie suggests, the api would be `table.primarykey` which would just be an instance of the `Key` class.

**Comment by karlcz** [comment]
Sorry I missed this the first time around and just heard about it in conversation...  I think it is a mistake to talk about "primary key" as a concept in ERMrest and Chaise as it is a SQL concept that doesn't really surface in our catalog model.  For most purposes, every key that is exposed in ERMrest model introspection is equally meaningful and particularly if it's constituent column(s) are constrained as not-null, then they really are equivalent from a data manipulation perspective.

The reason to choose one key over another is largely aesthetic and requires some use-case information. If Chaise has a need to choose a key for record-linking or other tasks, I think that should be implemented client-side in Chaise and/or ermrestjs as a simple hueristic to choose among the available keys on the table.  For example, you might just sort the keys based on several criteria:

1. Put all non-nullable keys before nullable, i.e. always use a non-nullable key if available
2. Put shorter key tuples before longer key tuples, i.e. prefer simple keys instead of composite
3. Order keys by their first constituent column position in table definition? Modelers often put their "important" keys first when defining tables...

The preferred key would be the first key in the sorted key list. The non-nullable part is the only part that really matters.  The others are just possible tie-breakers that might make for nicer URLs etc.

If simplicity of the URL matters and if making this decision for a single known record, you might even make a dynamic decision based on row values!  Any non-null value is equally valid as a key, regardless of whether the schema allows a null to appear.  And shorter text values, values without special characters, and/or smaller integer values might make for simpler/prettier URLs...

**Comment by robes** [comment]
This is probably a 'wontfix' issue for the time being, at least not in the way it was originally posed. We have done this sorting approach in the Chaise level BTW, and if its useful its something we should consider pushing down to ermrestjs.
