### ISSUE TITLE
supply a filtering criteria for related table reference

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#367]
We have decided that instead of rewriting the url for the related table references which only works for the direct in-bound foreign keys, but not the pure and binary association case, we will provide the filtering clue through a URL parameter.. 

What about using `filters` as the parameter name? 

Chaise will then just display what's in the parameter value and provides a reset button..

**Comment by karlcz** [comment]
I think the parameter name should be something like "subset" or
"subset_name" and its purpose is to provide a human readable subtitle
for the set of results being displayed in recordset.  It could be used
even in the future when we have breadcrumbs or faceting UI to show the
actual constraint values.

Also, I think the button name should be something like "show
unfiltered" rather than "reset".

**Comment by RFSH** [comment]
@karlcz Can you please specify the format of readable subtitle that we should show?

**Comment by karlcz** [comment]
The subset name should be an arbitrary string that the Chaise page can use as a subtitle below the normal title which I believe is the table name.

Let's assume:
- starting on record page for "parent" table T1
- navigating to recordset page for "child" table T2

Then, there are really only two ways we get related entity sets:
1. foreign key F1 points from T2 to T1
    - the "to name" for F1 names the kind of relationship to T1 we care about
    - the "row name" for the record page in T1 names the specific "parent" record we are filtering on
2. foreign key F1 points from association table A to T1 and foreign key F2 points from A to T2
    - the "to name" for F1 names the kind of relationship to T1 we care about
    - the "row name" for the record page in T1 names the specific "parent" record we are filtering on

Then, I think the subset name could be formed as any one of these possible sentence fragments:
- `where` _to name_ `is` _row name_
- `for` _to name_ _row name_
- `with` _to name_ _row name_

E.g. if I visit https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfDsy20170111A and then click view-more on the Image section I end up at an Image page. The Chaise page with subtitle might look like:

    Image
    for Subject ZfDsy20170111A

assuming the default _to name_ heuristics for the foreign key use the simple foreign key's column name `Subject` and the default _row name_ heuristics for the row use the simple key's value `ZFDsy20160111A`. 

I think the `for` phrase fits more naturally for basic foreign keys while the `with` or `where` might fit more naturally for association tables.  It would be useful for people to sketch out some examples from their own models and see if one name template works better than others.  We could even consider having an annotation to customize this naming template if it doesn't seem like one size can fit all cases...?

**Comment by karlcz** [comment]
I edited my previous message to include the `[show unfiltered]` button in the illustration.. this is something recordset would add after the subset name string, not something the caller embeds in the name itself.
@hongsudt @robes

**Comment by robes** [comment]
Seems fine to me. I would prefer if we don't need an annotation for the subtitle.

**Comment by RFSH** [comment]
@karlcz @hongsudt @robes These are the issues that I found related to related entities displayname.

The following are based on [karl's assumptions](https://github.com/informatics-isi-edu/ermrestjs/issues/367#issuecomment-288265834).


1. For simple related tables:
    - Based on #123, the "from name" of F1.
    - Otherwise, the display name of T2.

2. For association related tables:
    - Based on #139, the "to name" of F2.
    - Otherwise, based on #210, the displayname of association table (A).

**Comment by RFSH** [comment]
After discussion with @hongsudt, we think that using "to name" as @karlcz suggested makes sense in this case. In addition to that, we should use the displayname of T1 as a fallback (if "to name" is not defined).

I also have to mention that both table displayname and row name can be HTML. I am going to add another query parameter (subset_html) to indicate if we should treat it as HTML or not. Although it might not make any difference since it's exposed in the url and users can easily change it.

**Comment by karlcz** [comment]
I'm not sure I understand regarding HTML.

The display names may be HTML due to our markdown renderer.  If the DBA uses markdown that interferes with the page display, we'll say it's their fault and they should fix it (i.e. not using header styles in the markdown fragment).

The input from the URL paramter MUST NOT be interpreted as HTML.  It should be treated as plain text (going through the HTML escape logic).  I don't think we have analyzed the markdown renderer enough to trust it with arbitrary content from a URL.

**Comment by hongsudt** [comment]
for the sentence fragments, I think we should use one consistently.. Let's use 
- `for` to name = row name.
