### ISSUE TITLE
Move Session logic from Chaise to ermrestjs

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#370]
See this thread starting [here](https://github.com/informatics-isi-edu/chaise/pull/1025/files#r107788404) for more context. 

Chaise should use ermrestjs to get the session (e.g. `ERMrest.Session.get()`), log out, etc. so that this logic can use ermrestjs' retry logic.

**Comment by hongsudt** [comment]
@chiragsanghvi This issue seems to be what we have discussed about the session service on Thur.. 

* all the session management e.g. getting a new session, returning existing session, etc. should be centralized and moved to ermrestjs 
* the get session should be asynchronous. If a different session is returned, the app should throw an error and reset. 

@chiragsanghvi @jrchudy @karlcz  please add missing detail..

**Comment by jrchudy** [comment]
@karlcz made this point before, but I don't think the session APIs belong in `ermrestJS`. To get the session, we are making an `http` request directly to the `authn` API. `ErmrestJS` is meant for communicating with the `ermrest` API.

We can still do this, but `ermrestJS` will no longer be _just_ `ermrestJS` it will be `ermrest and some other APIs JS`.

**Comment by RFSH** [comment]
I am going to close this issue. It's not relevant anymore and even if we decided to go through this change, we don't need an issue for it.
