### ISSUE TITLE
default app_link

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#371]
Make sure that app_link is always defined..

**Comment by RFSH** [comment]
Since it is client's responsibility to provide the `appLink` function, we should
- Make sure that chaise is always returning an appLink. [Currently](https://github.com/informatics-isi-edu/chaise/blob/502721dac14c3c4f402c3194167a3fea76dffa49/common/utils.js#L154) it returns`undefined` in some cases.
- Change ermrestjs behaviour to return an error if it could not find the `_appLinkFn`.
