### ISSUE TITLE
support psuedo-column that is an inbound table  

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#401]
This will allow the related table to be displayed as part of the regular columns.. 

sketch out what need to be done

**Comment by RFSH** [comment]
### Reference.columns and Reference.related
If `visible-columns` annotation is not defined, we should not add any Inbound Foriegn Key to the list of columns. If this annotation is defined and includes inbound foreign keys, we should remove them from the `Reference.related`. These two attributes will co-exist, but should not include duplicate values.

### Inbound Foreign Key Pseudo Column
`ReferenceColumn` is a class that is used for `Reference.columns`. It wraps `Column`s. But in this case what we are wrapping is the related `Reference`, therefore the `ReferenceColumn` cannot be reused. I should create a new class that wraps `Reference` object. It should have the same attributes as `ReferenceColumn`, which are:
- `name`: Reference's name.
- `displayname`: Reference's displayname.
- `type`: We are using `markdown` for pseudo-columns. This one should be `markdown` too.
- `nullok`, `default`, `inputDisabled`: These attributes only make sense in entry contexts. Since we are not using this pseudo-column in entry contexts, they are not needed for this class.
- `formatValue` and `formatPresentation`: Chaise is not directly using these function. They are being used internally by `Tuple.values` to generate the values. But in this case, we don't have directly access to values. Instead there should be a attribute that returns the `Reference`. Then chaise has to call read on that and use it as the value.

** I might be able to reuse the `ReferenceColumn` class, I can decide more about this when I get to actually implementing it`

**Comment by RFSH** [comment]
This was implemented in #438 PR. This functionality has not been implemented in chaise yet.
