### ISSUE TITLE
File.lastModifiedDate is deprecated

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#414]
When trying to update an entity with an asset column, I see this warning output into the console:
`File.lastModifiedDate is deprecated. Use File.lastModified instead.`

As part of this, verify the purpose of this property and see if it's even necessary to track.

We should update the out file API appropriately.

**Comment by RFSH** [comment]
The only mention of this attribute in ermrestjs is when we are creating a `upload` object and more specifically in `upload.fileInfo` attribute.

I removed that attribute because we are storing the file in `upload.file`, then we can easily access file info using that object and `upload.fileInfo` is completely redundant.
