### ISSUE TITLE
Parser extension to support facets/filters

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#447]
To make it easier for us to pass the filters and parse them, we decided to encode the filters in chaise, then ermrestjs decodes it and creates a uri that ermrest understand. Therefore filter will be a JSON object. To make it easier to find this filter part, we can introduce a new operator, i.e. `::filters::`.

## Structure

The overall structure of filters is as follows. Each facet term combines a data source and constraint spec, and so all combinations of constraint kind and data source path are possible in the syntax.

```
<FILTERS>:  { <logical-operator>: <TERMSET> }

<TERMSET>: '[' <TERM> [, <TERM>]* ']'

<TERM>:     { <logical-operator>: <TERMSET> } 
            or
            { "source": <data-source>, <constraint(s)> }
```

In the following sections each of location operators, data source, and constraints are explained.

## Logical operators

We want the structure to be as general as possible, so we don't need to redesign the whole structure when we need to support more complex queries. Therefore as the top level, we can have logical operators.

    { "and": [ term... ] }
    { "or": [ term... ]}
    { "not": term }

## Data Source

The difference between base table columns and columns in related entities is just a difference in data source. It shouldn't involve a completely different set of filter structures.  Instead, the single filter structure should conceptually allow various forms of data source specification

    "*"
    "Column1"
    [{"inbound": ["S1", "FK1"]}, "Column2"]
    [{"inbound": ["S1", "FK1"]}, {"outbound": ["S2", "FK2"]}, "Column3"]

The simple form `"Column1"` might be allowed as a short-hand for `["Column1"]` since it isn't ambiguous. But any foreign key path also needs to end with the actual column that will be projected and filtered. The _direction_ field labels `"inbound"` and `"outbound"` remove any ambiguity for self-referencing table navigation scenarios. The constraint name pairs `["S1", "FK1"]` etc. reuse the same names appearing in the ERMrest model introspection document.

Even if we are faceting on a vocabulary concept and just want the user to pick values by displayed *row name* and we substitute the actual entity keys in the ERMrest query, I think we should record this column choice explicitly in the facet spec, e.g. `[{"inbound": ["S1", "Fk1"]}, "id"]` so that the resulting faceting app URL is unambiguous even if there have been subtle model changes in the interim, which might change the default key selection heuristics etc.

> Based on this, we are not supporting filtering on foreign keys with composite keys.

### entity v.s. scalar facet
The source with fk path can either be presented as a scalar column or an entity picker. Unless set by `"entity facet":true`, the facet should be treated as a scalar column. 

    "entity facet": true

### Specific occurrences of rows

If we ever need to model a set of constraints where the same related entity  row must simultaneously satisfy multiple facet constraints, we could add an optional instance identifier to the path elements:

    [{"alias": "child A", "inbound": ["S1", "FK1"]}, "Column2"]
    [{"alias": "child A", "inbound": ["S1", "FK1"]}, "Column3"]

When querying ERMrest, we would detect that the same instance ID is in use and map these to constrain the *same* joined table instance in the query. By default, each path element without a pre-assigned ID should get a new, unique ID assigned. Thus, every source path would imply a different joined table instance for each separate constraint.

Some extra validation work may be needed once we introduce specific occurrence IDs. For example, the same instance ID cannot be assigned to elements at different depths in a source path nor to elements with different constraints. All paths with shared IDs must be identical in structure for the shared components, but may branch off with unshared suffixes.

## Constraints

We're only talking about three kinds of constraint right now:
1. Discrete choice e.g. maps to a checklist or similar UX
2. Half-open or closed intervals, e.g. maps to a slider or similar UX
3. Substring search, e.g. maps to a search box UX

Conceptually, this should correspond to three possible syntactic forms:

    {"choices": [ value, ... ]}
    {"ranges": [ {"min": lower, "max": upper}, ...]}
    {"search": [ "box content" ]}

A half-open range might be `{"min" lower}` or `{"max": upper}`.

We expect multiple disjunctive choices or ranges, so I show lists. Search UX may only have one search box but we can use a list here for consistency of the internal model.

### Mix-ins

If a multi-modal facet control UX is available, we might even mix-in several forms of constraint on the same source. We also probably need a way to specify the preferred `ux mode` when the facets are first rendered. For now, these options are `choices`, 'search`, or `range`. We can change these values when we are done withe the UX. :

    {"source": "Column1", "choices": ["outlier"], "search": ["sub"], "ranges": [{"min": "xylephone"], "ux mode":"choices"}

The mixing of several constraints would be disjunctive to be consistent with the disjunctive list of options in each constraint.

## Examples

- Consider this logical filter set:
    - and
       - column1 multi-choice 1, 2, 3
       - column2 across S1:FK1 range [5,10]

    It can be encoded in the following JSON using the above abbreviation techniques:

        {
          "and": [
            {"source": "column1", "choices": [1, 2, 3]},
            {"source": [{"inbound": ["S1", "FK1"]}, "column2"], "ranges": [{"min": 5, "max": 10}]}
          ]
        }

    Which will be translated to the following in ermrest syntax:

        /M:=S:T/(column1=1;column1=2;column1=3)/$M/(fk)=(S1:T2:key)/(column2::gt::5&column2::lt::10)/$M
    
- A more complex example that this structure can support but as the first implementation we are not supporting:

JSON object:
    
        {
            "and": [
                 {
                     "or": [
                         {"source": "c1", "ranges": [{"min": 1, "max": 5}]},
                         {"source": "c2", "choices":[1, 2]}
                     ]
                 },
                 {"source": [{"inbound": ["S1", "FK1"]}, "c3"], "search": ["text"]}
            ]
        }

which translates to:

        /M:=S:T/(c1::gt::1&c1::lt::5);(c2=1;c2=1)/$M/(fk)=(S1:T2)/(c3::ciregexp::text)/$M

**Comment by karlcz** [comment]
I don't really understand this:

    /Schema:Table/<key=value pairs>/<join(s)>/<filter(s)>/<search>/<sort>/<page>

I don't think these should be thought of as separate sections:

- key value pairs
- filters
- search

Rather, I think we need to implement a parser for filtering in general:

- key, operator, value filter terms
   - the `=` operator is just one case
- conjunction, e.g. the `/` and `&` separators in ERMrest
- disjunction, e.g. the `;` separator in ERMrest
- pseudo operators for special cases?
   - `::search::` the text search-box entry that gets compiled to regexp query
   - `::between::` shorthand for a conjunctive upper and lower bound?
   - `::any::` shorthand for a disjunction of many value choices?
- negation via the `!` prefix
- grouping/nesting, e.g. `(` ... `)` in ERMrest

Then, we should refactor the individual places that use the output of
the parser so that they all use the same kind of Filter object in
JS. There could be convenience APIs in ermrestjs to ask whether the
filter/reference is in the expected standard or restricted form for
certain use cases.

**Comment by karlcz** [comment]
Sorry, I just had a chance to finish looking at this.  I think some parts need a bit more tweaking.

## Logical operators

You implicitly assume a conjunction of individual facet constraints. It might be better to make this explicit in the notation, so that if we want to support disjunction in the future, that uses a complementary syntax rather than requiring all syntax to be redefined.

    filters = { "and": [ term... ] }

## Constraints

As far as I have heard, we're only talking about three kinds of constraint right now:
1. Discrete choice e.g. maps to a checklist or similar UX
2. Half-open or closed intervals, e.g. maps to a slider or similar UX
3. Substring search, e.g. maps to a search box UX

Conceptually, this should correspond to three possible syntactic forms:

    {"choices": [ value, ... ]}
    {"ranges": [ [lower, upper], ...]}
    {"search": "box content"}

A half-open range might be `[null, "upper"]` or `["lower", null]` if we have need a UX element that supports these?

I think we expect multiple disjunctive choices or ranges, so I show lists.  I don't think we would have disjunctive search boxes but just one string holding the whole search box content which might include multiple words?

## The data source

The difference between base table columns and columns in related entities is just a difference in data source. It shouldn't involve a completely different set of filter structures.  Instead, the single filter structure should conceptually allow various forms of data source specification

    ["Column1"]
    [["Schema1", "Fkey1"], "Column2"]
    [["Schema1", "Fkey1"], ["Schema2", "Fkey2"], "Column3"]

The simple form `"Column1"` might be allowed as a short-hand for `["Column1"]` since it isn't ambiguous. But any foreign key path also needs to end with the actual column that will be projected and filtered.

Even if we are faceting on a vocabulary concept and just want the user to pick values by displayed *row name* and we substitute the actual entity keys in the ERMrest query, I think we should record this column choice explicitly in the facet spec, e.g. `[["S1", "Fk1"], "id"]` so that the resulting faceting app URL is unambiguous even if there have been subtle model changes in the interim, which might change the default key selection heuristics etc.

## Adding source to constraints to define a facet term

Each facet term combines a data source and constraint spec, and so all combinations of constraint kind and data source path are possible in the syntax.

    {"source": "Column1", "choices": [value, ...]}
    {"source": "*", "search": "some text"}
    {"source": [["S1", "FK1"], "Column2"], "ranges": [ ["lower", "upper"], ...]}

## More compact notations

If we really want to scrunch the space out of the JSON used in the URL, we could combine several hacks:

1. Use positional arrays for facet term objects to avoid repeating field names
2. Infer constraint type from syntax
   - A bare string `"search text"` must be the literal for a search-box constraint
   - A flat array of literals `["value", ...]` must be the literals for a multi-choice constraint
   - An array of arrays `[["lower", "upper"], ...]` must be the literals for a range constraint
3. Abbreviate field names like logical combiner
   - `"a"` for *and*
   - `"n"` for *not* (if we need negation)

## Examples

Consider this logical filter set:
- and
   - column1 multi-choice 1, 2, 3
   - column2 across S1:FK1 range [5,10]

It can be encoded in the following JSON using the above abbreviation techniques:

    {
      "a":[
        [
          "column1",
          [1,2,3]
        ],
        [
          [["S1","FK1"], "column2"], 
          [[5,10]]
        ]
      ]
    }

Which is the same as this with all whitespace omitted:

    {"a":[["column1",[1,2,3]],[[["S1","FK1"],"column2"],[[5,10]]]]}

Which is this ugly string when using safe URL encoding:

       %7B%22a%22%3A%5B%5B%22column1%22%2C%5B1%2C2%2C3%5D%5D%2C%5B%5B%5B%22S1%22%2C%22FK1%22%5D%2C%22column2%22%5D%2C%5B%5B5%2C10%5D%5D%5D%5D%7D

Note that our 64 byte string got inflated to 138 bytes of visual clutter due to all the URL encoding triplets.

## Other encoding techniques

To make this smaller, you'd like to make some changes:
1. Replace curly braces `{` and square brackets `[` with parenthesis `(`
2. Avoid URL-encoding parenthesis, colon, and comma
3. Drop string quotes where they are not needed, e.g. on strings that don't themselves have parenthesis, colon, comma, or whitespace

Then the preceding string would look like this:

    (a:((column1,(1,2,3)),(((S1,FK1),column2),((5,10)))))

and this could actually appear in a URL fragment ID without URL-encoding all the meta-syntax made out of parentheses, commas, etc.  However, at this point you no longer have the benefit of using a standard JSON decoder so I don't think it is worth it.  We could instead invent a smaller set of extensions or idioms around the current ERMrest syntax and write a parser for it...

**Comment by robes** [comment]
Comments on sections above:
- Logical operators: I can kind of see the point to making it explicit, but I'd like to see how this relates to the UX. I'm not sure we have any plans to have a full query builder with logical expressions. It doesn't hurt to use this syntax but not sure its necessary.
- Constraints: Overall good improvement over the initial draft by Aref. Only I thought that "search" could have multiple values. That was in our earlier drawings on the UX. So this might need to be `{ "any | all": [ "search text", "search text 2", ... ] }`
- The data source: Agree, we should have the column projection listed explicitly.

I feel like we might be missing some concept here that is implicit. We may need to first visit the facet annotation spec (which may not exist right now). Just using source may not be enough to identify the facet if for example a column can appear a two different facets.

**Comment by karlcz** [comment]
I thought "search" would correspond to the search box.  It's a single
string you'd be able to reload back into the search box on app restart
from a permalink.  Having a variable list of these would imply a
variable list of search boxes and I don't see where we'd have such a
UX...?

The source as a chain of foreign keys terminated with a column
projection is meant to cover all possible "remote columns" used as
independent facets.  These would correspond 1:1 with things we could
put in the faceting side-bar in the UX and correspond to existence
of a linked entity with that specific column constraint.

What this cannot express is quantified sub-query scenarios, with
multiple facets drawing from the same joined table instance. I.e.
existence of a specific linked entity which simultaneously satisfies
constraints on several different columns.

That would be a more advanced form of query and I don't think we have
any idea how to do the UX right now.

I guess you'd either need to model table instances (specific
occurrences) which scope several facet controls, or you need a facet
control that looks like a sub-query, e.g. the facet means "this other
related entity set is non-empty" and that one is also formulated as a
faceted query...

**Comment by robes** [comment]
Re: search. I see. I was thinking this 'search' was for the text search facet that Hongsuda wanted not the top level search boxes. We have two scenarios for search but maybe we can give the faceting form a distinct name.

Re: the rest, I can explain better in person tomorrow.

**Comment by karlcz** [comment]
I updated the long comment above again...

**Comment by RFSH** [comment]
Updated the issue description based on the comments and deleted the comments for readability.

**Comment by robes** [comment]
@RFSH I feel like the pseudo-BNF and the last example are a little wrong. E.g., the nested array in the last part of the last example seems off.

**Comment by robes** [comment]
Maybe the BNF should be closer to this:

```
<FILTERS>:  { <logical-operator>: <TERMSET> }

<TERMSET>: '[' <TERM> [, <TERM>]* ']'

<TERM>:     { <logical-operator>: <TERMSET> } 
            or
            { "source": <data-source>, <constraint(s)> }
```

And then the last example JSON object:
    
```
        {
            "and": [
                 {
                     "or": [
                         {"source": "c1", "ranges": [{"min": 1, "max": 5}]},
                         {"source": "c2", "choices":[1, 2]}
                     ]
                 },
                 {"source": [{"schema": "S1", "constraint": "FK1"}, "c3"], "search": ["text"]}
            ]
        }
```

**Comment by RFSH** [comment]
There are two concerns that came up with this structure:

1. Just having a list of constraint names can cause ambiguity. We should specify the direction of each join.

2. We decided to change the current url structure that we are using for related entities to use faceting. But the proposed structure only supports simple foreign keys.

**Comment by karlcz** [comment]
If we want to make the facet paths consistent with the fine-grained, dynamic ACL binding notation in ermrest, we need to make the following changes:

1. The source path is a list of path elements ending with the source column, i.e. drop a layer of nested lists from the current issue description.
2. The direction of each foreign key navigation in the path should be explicit.
3. The constrain name should be a simple list `[Schema,Constraint]` as in the ermrest schema introspection.

Here would be an example path using both possible directions:

    [{"inbound": ["S1", "FK1"]}, {"outbound": ["S2", "FK2"]}, "My Column"]

Finally a composite "parent entity" key could be expressed with facets since each component would map to a different facet in the conjunctive facet list.  You do not need a single facet representing the entity choice but can just expose each component value as a scalar facet.  This would only occur for backwards compatibility with old recordset URLs.  Going forward, we are going to require simple primary keys on all tables and hence can always define related entity constraints as a single facet control state.

**Comment by karlcz** [comment]
By the way, another bit of path syntax from ermrest ACL bindings would be to include table instance aliases. This is **not** necessary for the MVP but if we ever want to allow several facets to be defined to share the same intermediate table instances, we should reuse this syntax and use a logic where we build the join to share a common table instance if multiple facets assign the same alias.

- The path element object has an optional field `"context"` which can reference a table instance alias other than the default which is the one immediately left of it in the path.  This is analogous to the `$Alias` path reset notation in ERMrest join paths.
- The path element object has an optional field `"alias"` which can assign an alias to the newly joined table instance.  This is analogous to the `Alias:=` binding notation in ERMrest join paths.

So, a completely explicit path example might look like this in the future:

    [{"inbound": ["S1", "FK1"], "alias": "A"}, {"context": "A", "outbound": ["S2", "FK2"]}, "My Column"]

the binding and use of "A" above wouldn't actually change the meaning unless another facet definition also included the same first element, in which case they would both share the same table instance "A" instead of each one joining on a separate copy via the same foreign key.

**Comment by karlcz** [comment]
I made an attempt at updating the issue description based on my preceding comments.

**Comment by RFSH** [comment]
@karlcz 
Why not adding direction as a separate attribute  `{"direction": "inbound", "constraint": ["S1", "FK1"]}`?

**Comment by karlcz** [comment]
Because I am trying to make this consistent with an already existing
implementation of path syntax in the ERMrest fine-grained ACLs system,
so that a DBA doesn't have to learn two different path notations.

All the elements I added in the edits today are existing features of
the ERMrest ACL system:

- flat list of join elements ending with a column name for projection
- direction as `"inbound"` or `"outbound"` object field names
- constraints named by the pair `[S,N]`
- optional `"alias"` to bind a table instance alias
- optional `"context"` to reset path context explicitly

**Comment by hongsudt** [comment]
@RFSH @karlcz I updated the `ux mode` under mixin and `entity facet` under source.

**Comment by RFSH** [comment]
Created a wiki page based on the comments in this thread: https://github.com/informatics-isi-edu/ermrestjs/wiki/Facets-JSON-Structure
