### ISSUE TITLE
submit an unchanged record (edit mode) caused bad request error

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#458]
Here is the URL. 
https://dev.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:Sample/Accession_ID=RBKUSC20170719SAM2@sort(Accession_ID)

Here is the error
Error 400 Bad Request The request is malformed. URL parse error at token: LexToken(?,'?',1,77) 

If I changed at least one field, the submission was successful.

**Comment by karlcz** [comment]
When there are no changes in the form, the submit button should be 
disabled since it makes no sense to submit no changes...

**Comment by jrchudy** [comment]
As @karlcz is suggesting, that should be the more appropriate change. After modifying the code to not add the `;` after the key set when there is no projection set, you get a 400 error from `ermrest`

`400 Bad Request The request is malformed. Grouped attribute update requires at least one target attribute.`

**Comment by jrchudy** [comment]
Or, do we want to allow the user to try to submit the data and have this error be displayed to the user in `recordedit`?

**Comment by jrchudy** [comment]
The temporary solution to this issue is to have `ermrestJS` return an error that is displayed as a warning message on the `recordedit` app. This doesn't submit the data and instead let's the user look over the data and make changes.

A user is not allowed to update data without any changes being made.
