### ISSUE TITLE
Reference.update doesn't check all values for changes properly

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#463]
When the column is of type `date`, `timestamp`, or `timestamptz`, the check to make sure the values have changed before adding the column name to the list of projections may not work properly.

When I saw this issue, I had a `timestamp` column with:
 - old value = `2016-01-18T13:00:00`
 - new value = `2016-01-18T13:00:00.000-08:00`

The `timestamptz` column had these values:
 - old value = `2016-01-18T00:00:00-08:00`
 - new value = `2016-01-18T00:00:00.000-08:00`

One way to fix this is to convert values for these column types using moment and then compare the values.

**Comment by hongsudt** [comment]
@jrchudy Is this still an issue?

**Comment by jrchudy** [comment]
This is still the case and should be addressed to prevent losing precision for timestamp values.

**Comment by RFSH** [comment]
Since the check in update function is a simple `old !== new`, it will also not properly handle cases where the user's timezone differs from the server's. This is not causing any data loss but will trigger an unnecessary update.

For example, assume the server is in Log Angeles, and the user is in  New York. In this case, the `entity` API would return the `timestamptz` values like `2023-02-02T11:00:00-8:00`, but since we're converting this time to be based on the user's timezone, the submitted data without any change would be `2023-02-02T7:00:00-8:00`.
