### ISSUE TITLE
row-level ermrest ACL support

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#487]
@karlcz what are the steps do we need to do to migrate to the new ACL in ermrest?

**Comment by karlcz** [comment]
If you are on latest ermrest master you already have the fine-grained
ACL features.  You can see evidence of them as various "rights"
documents embedded inside the main /ermrest/catalog/N/schema/ response
document.

To make the front-end adapt to fine-grained rights, it should start to
consult those "rights" documents on each part of the model. At the
table level:

- select: is client allowed to query the table
- insert: is client allowed to insert new rows
- update: is client allowed to edit existing rows
- delete: is client allowed to delete existing rows

The answers can be true/false/null.  A null means that the access
decision is data-dependent (i.e. row-level policy) and cannot be
advertised statically for the entire table.  It may succeed or fail
on specific rows.

The column-level version of these rights says whether that particular
column can be addressed in select, insert, or update operations. You
might map this to ermrestjs concepts like:

- insert false: column is "generated" during row insert
- update false: column is "immutable" during row edits

Similarly, if column-level select rights are false, the column should
be dropped from any visible columns list since it will cause a
forbidden error if included.

**Comment by hongsudt** [comment]
From the meeting today, we decided to: 
- [ ] handle table right policy for canCreate, canUpdate, canDelete, canRead
  - null value should be treated as true.
- [ ] column level policy
  - insert false: column is "generated" during row insert 
  - update false: column is "immutable" during row edits
  - select false: show `--hidden--` for the formatted value
- [ ] rename canCreate to canInsert to be consistent with ermrest terms
- [ ] rename canRead to canSelect to be consistent with ermrest terms

**Comment by hongsudt** [comment]
take a look at the epic associated with this issue. Karl has provided information on the new right in the epic.

**Comment by chiragsanghvi** [comment]
Select for columns will be taken care by ermrest as mentioned in this issue https://github.com/informatics-isi-edu/ermrest/issues/167
