### ISSUE TITLE
extension of pure and binary assocation definition

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#488]
Ermrest will be adding row_id, creation_timestamp, last_modified_timestamp, created_by, modified_by to every table.  We need to extend the pure and binary association definition to support this. 

I would like to extend this definition further by allowing arbitrary scalar columns in this association table, so that they can be used to track deployment specific system information (which are usually not shown to the users). An idea is to use visible columns (instead of based columns) when determining whether a table is pure and binary.  

@karlcz @robes What do you think?

**Comment by karlcz** [comment]
Using visible columns might work, but which context(s) need to be
checked for such a heuristic?

Columns can be hidden at the model level via the `enumerate` ACL on
each column.  I think that if you hide your system column this way,
ermrestjs would just think the table is simpler.  Don't try to hide
a column that has not-null constraints though!

If you need ermrestjs to be aware of the columns (i.e. to tip-toe
around them) you could grant `enumerate` so the columns are visible in
the model but withold `select` rights so the client cannot query them.
Then ermrestjs would have to inspect the reported column-level rights
in a modified heuristic.

An advantage of trying to use fine-grained ACLs for this is that you
could expose a different UX to different classes of user depending on
whether you hide the columns or not.

**Comment by robes** [comment]
Responding to @hongsudt 's initial question: What would you propose as the _default_ heuristic? If chaise+ermrestjs encounter a table with `system columns...` + `fk1` + `fk2`, would it at least have a default heuristic to consider that a pure, binary association table without any additional annotations (or ACLs) so that we reduce the data modeler burden?

Regarding ACLs vs Visible Columns annotations, I haven't formed an opinion. But I'm wonder what kinds of interactions we have with these system columns and whether those interactions would be disrupted by an ACL approach (making them invisible to say IObox/derivapy and not just Chaise).

**Comment by robes** [comment]
Okay, so here's an alternative proposal to consider... how about a new annotation (to be defined) on the table to indicate explicitly that it should be treated like a pure binary association (in such cases the annotation would be invalid if there were anything other than exactly 2 FKs).

**Comment by hongsudt** [comment]
I would like to discuss this at standup meeting tomorrow.
