### ISSUE TITLE
Multi-add: Exclude subset of entries already added in association. 

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/ermrestjs#490]
The issue stems from [this](https://github.com/informatics-isi-edu/chaise/issues/1231) chaise issue. While adding multiple records in case of pure and binary association we should exclude entries that have been previously added. 
The solution will require changes in selection for the related table items where we need to exclude entries that already exist in the association table.

**Comment by amitjha21** [comment]
One suggested approach is to create a left outer join of the reference table with association table and use a filter to select entries with `null` in the primary key column from association table.



![exclusion_1](https://user-images.githubusercontent.com/9977014/30079162-2a8b6c38-9234-11e7-95e0-19636fb6fcaf.jpg)

**Comment by karlcz** [comment]
That's right except the right-hand side of the example should read `/id1::null::` to use the actual ermrest operator name and to constrain the other fkey field of the association table.

**Comment by karlcz** [comment]
Actually, let me be more explicit...

    /R:=S:R/left(id2)=(A:id2)/id1=X&id1::null::/$R
   
    /M/id=X/A:=(A:id1)/right(id2)=(R:id2)/A:id2::null::

- You need to limit your join to only considering associations to the same main record `X` that you actually care about for exclusion, not all associations to other records in the `M` table.
- You need to either reset the path context back to the domain table `R` or use a right outer join so that the domain table can be on the right side of the path. The right join might be easier to think about in the general case where the parent key `X` and the association fkey back to the main table `M` may not actually use the same key column.

**Comment by karlcz** [comment]
I looked into this more, and I don't think the query behavior we want is possible with the current ermrest API.

We can do the following queries:
1. All domain values (what we have now)
2. All domain values that match static pattern (what we have now with domain filter patterns)
3. All domain values that are already associated with parent (inner join with parent record filter)
4. All domain values which are not associated to *any* parent (outer join with null filter)

But we cannot do:
- All domain values which are not associated with a specific parent

This is because all ermrest filters are rendered in the `WHERE` clause in SQL which filters out the resulting rows of the join.  It is not possible to simultaneously filter for a specific parent ID (to constrain the join to only a certain parent) and a NULL parent ID (to select only domain rows included via the outer join).  Expressing both will always result in an empty result set.

The query we want will require new ermrest URL syntax to either specify filtered subqueries in the join or to add filters to the join condition itself rather than to the final row set.  No such work is scheduled right now, so I think this issue needs to be parked.  There isn't any reasonable client-side workaround for large domains...

**Comment by amitjha21** [comment]
As per discussion:
For each page in modal pop-up we have to make two calls each to association and reference. Disable common values between them and allow users to check/uncheck unique values only.

**Comment by amitjha21** [comment]
Test query to get all association entries against given leaf entry:

https://dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/L:=isa:experiment_type/R:=left(term)=(isa:dataset_experiment_type:experiment_type)/$R/experiment_type;L:=array(R:*) 

https://dev.isrd.isi.edu/ermrest/catalog/35257/attributegroup/L:=multiadd:leaf/R:=left(id)=(association:ak2)/$L/id,Items;A:=array(R:*)  : _test data_

**Comment by amitjha21** [comment]
The suggested approach is to handle it through single call to get all rows without filter as mentioned above for efficiency and scalability. Then go through the resultset to pick out rows that are already added to the association. This would require changes in API at Ermrest level. This is parked for now.

**Comment by RFSH** [comment]
I tried the method of adding extra column to the projection list. That method had performance issues and we decided to use the two request method. Which is on each read for getting the domain values, we should do another read to get the existing values. The only caveat is that this new request must be using the same paging as the domain values.
