### ISSUE TITLE
Hierarchical annotation behavior

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#53]
Annotations such as `sparse` (to be determined) may be specified at multiple levels of the catalog - schema - table - column hierarchy. We need a pattern for how we decide which annotation value is defined at the level of interest. I.e., clients wants to know if a column should be shown when its values are null, the annotation api should interpreted at the higher levels of the hierarchy and the api should decide which final value overrides upper levels.

**Comment by robes** [comment]
Open question is whether we can apply the same logic across different annotations. E.g., can we handle the `null/sparse` annotation hierarchy in the same way as the `ignore` annotation?

**Comment by karlcz** [comment]
Also consider the draft I just added to 2015:display where I discuss hierarchy.  I think what I specified is intuitive to a user but requires more complex processing support.  Rather than a whole annotation payload overriding a whole annotation payload, I'm suggesting field-by-field override in this case.

I think that implementation support for this would require an explicit policy table to define how to compute overrides for specific annotation URI keys.

**Comment by robes** [comment]
I had been thinking about this too. We need to take a step back and decide whether its something that should be handled on a per-annotation basis. I’d rather not have a policy table have to describe this, and yet I agree and understand that whole annotation replacement (blindly) is not the right answer either. It could be this issue should be closed and handled per-annotation, if there’s no uniform way of doing it anyway.

**Comment by robes** [comment]
I think this issue is subsumed by other things we are doing like the contextualize interface. And the 'hierarchical' logic is not necessarily a general thing but specific to the interpretation and heuristics of individual annotations.

But please re-open if you disagree.
