### ISSUE TITLE
Distinguish between null vs false in the null guarding syntax e.g. {{~colname}}

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#539]
* @chiragsanghvi mentioned that {{~colname}} covers both null and false. Check this. 
* If so, we need a way to distinguish between false and null.. 
* Investigate handlebar but we might want to disable features that we don't need for security concerns.

**Comment by karlcz** [comment]
I think we should broaden this if possible.  I think a DBA wants to check for `NULL` that is due to the structure of their ERM and handle that case differently from all other cases. It's not just `false` but also zero, empty string, and I'd argue even empty lists and empty objects.

Another frustration I have with the current templates is that the same guard syntax turns into an iterator. You can't choose whether to test for presence of a list or object and then optionally decide whether you want to iterate its content or just do something with the whole value.

One example I've encountered is wanting to test a raw JSON column for whether it is NULL, and then substitute the "presentation" form of the column which is a pretty-printed JSON as markdown string.  If I try to use the guard statement, I'll potentially get an iterator that fires several times and duplicates the presentation value that many times!

**Comment by chiragsanghvi** [comment]
Add handlebars support to take care of null checks as mentioned above.
