### ISSUE TITLE
File upload error on checksum mismatch

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#554]
A user has reported failures on uploading largish files (~1GB) using the browser (chaise+ermrestjs).

First, the message from the browser hints at a checksum mismatch.

![browser - screen shot 2017-11-03 at 3 29 42 pm](https://user-images.githubusercontent.com/4202842/32919233-e201021e-cad9-11e7-98d7-f6509c2a86cf.png)

Network tab of developer tools shows a couple chunks in "cancelled" state.

![network - screen shot 2017-11-16 at 12 16 39 pm](https://user-images.githubusercontent.com/4202842/32919246-ea36e624-cad9-11e7-8fa4-a0ff10e1567c.png)

And then a screen shot of the console output for what its worth.

![console - screen shot 2017-11-16 at 12 17 21 pm](https://user-images.githubusercontent.com/4202842/32919268-03e09732-cada-11e7-8f28-9e545c7b88e9.png)

**Comment by chiragsanghvi** [comment]
@robes 

I just tried uploading a file to hatrac which is of size 1.4GB and it worked. Could you mention the extension of the file and maybe the file itself.

**Comment by hongsudt** [comment]
@robes They have a hard time replicating this issue. Can you give steps and file examples, so @chiragsanghvi can proceed with bug fixes?

**Comment by robes** [comment]
It is not a consistently reproducible error. I even had this user join me on a bluejeans call so that we could watch the process together with dev tools open. (Because I was unable to reproduce it.)

He had just encountered the error on a file before our call, and when I was on the call with him, the upload of the exact same file worked. So I do not believe this is file name, file format, etc. specific.

I think to attempt to reproduce, you should test on a slower network. This user was getting upload rates that varied between 270KBps and 3.3MBps as I watched. You might also try inducing errors (temporary/quick network outage) during a transfer, if that hasn't already been thoroughly tested.

If you cannot reproduce this bug, then the next step is to print a lot more diagnostics into the javascript console so that we can collect more information from our users the next time it happens.

Since we are getting an error that suggests the checksum is off, for e.g., print the checksum to the javascript console after you compute it, then print it at the end, when you get an error like this print the things that didn't match. Etc. Just put in enough breadcrumbs. 

There will always be some bugs that only our users will encounter and one school of thought is that you should leave in logging in production code just for situations like this. Not all bugs will have simple repeatable steps to reproduce in our environment.

**Comment by karlcz** [comment]
@robes Can you confirm one significant point with the user?  They SHOULD NOT attempt to upload a file that is potentially being modified simultaneously by any other processes on the client side.  This would look the same as any other form of corruption from the point of view of our end-to-end integrity checks.

**Comment by karlcz** [comment]
In any case, I think it would be worth logging what the uploader is doing:

1. Log the file that was selected and whatever metadata we can obtain (e.g. size and last modified if available via the file api)
2. Log the md5 we compute prior to upload
3. Log the file metadata again after the upload (size and last modified)

A more expensive thing would be to catch the error and repeat the local MD5 and log it too, to distinguish the case that the file appears mutated on disk rather than corrupted in flight.

**Comment by karlcz** [comment]
BTW, the wrinkle is that if we are using a chunked upload job, we can send chunks out of order and cannot recompute a running checksum of the bytes sent as another confirmation.  To do that, we'd have to serialize the chunk processing which would erase the benefit of parallel chunk transfer on slow networks...

**Comment by chiragsanghvi** [comment]
This is an issue with the browser or the server.  If you check the network log

![picture below](https://user-images.githubusercontent.com/4202842/32919246-ea36e624-cad9-11e7-8fa4-a0ff10e1567c.png)

There're 2 requests that got cancelled. This might be because the server didn't respond or the connection was aborted. HTTP doesn't allows us to identify cancelled or aborted requests easily.  They both have status code `-1`.

Our code doesn't handle this and considers it as a success and goes ahead with sending the  complete upload job request. This request ends up with a response mentioning there is a checksum mismatch.

**Comment by jrchudy** [comment]
Not sure how I can reproduce this issue. I tried changing my network speed (switching that in the dev console) and intermittently turning off the connection and turning it back on.

In the first case, I was able to see the chunks take a long time to upload, but didn't experience any issues with multiple chunks being uploaded and being reorganized improperly (potential mismatch of md5).

Int he second case, if it was intermittent enough (a quick off then on again right away), there was no issue with the job continuing. If the network connection was lost for a slightly longer period of time, a `No Connection Error` is thrown.

**Comment by hongsudt** [comment]
Do we have the logs that @karlcz suggested above? Does that log go to our server? If not, maybe we can use the same logging mechanism as the terminal case to log that on the server and observe the frequency that this problem is seen.

**Comment by jrchudy** [comment]
Logging the other information for the file upload requests has been done. Not sure what else we can do but to wait for the user to notify us when it happens again.

**Comment by jrchudy** [comment]
I was able to reproduce this issue with the following scenario:
Setup:
  - Have 2 files/namespaces that already exist in hatrac. This was done using the same namespace but 2 different files.
  - file 1 has name like `name_1.jpg`
  - file 2 has name like `name 2.jpg`

Steps (this was found when using the test suite. Notably the recordedit-add spec using the 2nd table, File):
  1. fill out the first form and select file 1
  2. click + to add a second row
  3. leave all the fields the same except the selected file
  4. select file 2
  5. submit the data
  6. md5 mismatch error should appear

Note: Both file 1 and file 2 should not be re-uploaded in this case because both already exist. There is an inconsistency with hatrac right now (explained in this [issue](https://github.com/informatics-isi-edu/hatrac/issues/48))where a file uploaded to hatrac with a filename with a whitespace in it, will have a returned filename with an underscore instead of a space.

**Comment by karlcz** [comment]
The hatrac service does not rewrite spaces as underscores, so this
would have to be part of the uploader code in ermrestjs.

More importantly, hatrac deals in URLs not filenames, other than in
the content-disposition header, which can carry a client-side filename
hint.

All hatrac object names are URLs and URLs cannot have spaces in them.
So, no matter what, some rewrite should be expected here if inserting
user-generated content into the requested object name.

This rewrite must be performed by the client code before it tries to
talk to hatrac, or it would likely get HTTP errors.  Generally, I
would have expected normal URL encoding (e.g. %20 instead of a space)
rather than an underscore.

**Comment by jrchudy** [comment]
Looks like it's neither `ermrestJS` nor `hatrac` that's changing the filename. This morning @hongsudt mentioned that there are different rules that apply to encoding in headers than encoding in URLs. 

Regardless, I spent some time trying to reproduce the error I reported on Friday above, and cannot reproduce it.
