### ISSUE TITLE
Error messages with table/schema level details

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/ermrestjs#571]
We need to have table details for users to take corrective action when they see errors.
- [ ] Table name along with column details
- [ ] Handle invisible columns names

**Summary**
- We should change this to show the displayname of related reference.
- If we cannot find the displayname then should show the name that ermrest is returning
- use flag to make sure it is being passed from `delete` function
- In the case that we couldn't figure out the related reference's displayname we should append a message that says "If you have trouble removing dependencies please contact the site administrator." to the error message that we generate.

- Test case for pure and binary association. An example of table definition can be found here

-  Test case for the case that you couldn't find the table displayname given the constraint name and table name. In the mocked response use an arbitary constraint name.

- Test case for when the error is being generated from somewhere else. This might not happen in ermrest but we can mock the server response.

- Test the actual displayname of the related entities:

     - In case of pure and binary association, define a to_name on the foreignkey to the related entity. Displayname should be that one.
    - In case of related, define a from_name on the foreignkey.

**Comment by RFSH** [comment]
This is only related to the `IntegrityConflictError`, which we are throwing when user is deleting a table that has some foreign key to:

 Currently if we can parse the message, we are showing the table name that ermrest is returning. We should change this to show the displayname of related reference. We have access to the table and also the constraint name of the foreign key. If given these two we can find the displayname we should change it, otherwise we should show the name that ermrest is returning.

Also we are assuming that this error will only going to happen in delete case, but we're not checking for it. We should change the `_responseToError` to accept a parameter that makes sure that we are doing this logic only in case of delete (You need to pass that argument in the error case in delete function in ermrestjs).

**Comment by RFSH** [comment]
In the case that we couldn't figure out the related reference's displayname we should append a message that says "If you have trouble removing dependencies please contact the site administrator." to the error message that we generate.

**Comment by amitjha21** [comment]
This has been merged. Assigning to @hongsudt  to verify and close it.
