### ISSUE TITLE
No value should not show up in compact

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#583]
https://dev.rebuildingakidney.org/chaise/recordset/#2/Gene_Expression:Specimen_Thumbnail_Display@sort(ID)

The above link lead to a recordset that shows No Value. We only have this problem on Dev, so it is probably due to a recent commit.

We shouldn't ever show *No Value* in the compact context, only in the compact/select!

**Comment by jrchudy** [comment]
This issue is being caused because of the changes made right before christmas break for showing nulls and filtering on only values that are not null.

What's happening:
The `uniqueId` for each tuple is being calculated to be `null`. The shortestKey is being defined as the `RID` column because the `tuple.uniqueId()` function thinks the table being used is `Specimen` and not `Specimen_Thumbnail_Display`. The available data which is from the `Specimen_Thumbnail_Display` table does not include an `RID` value.

The `shortestKey` for the `Specimen_Thumbnail_Display` is calculated appropriately to use `ID` column (because `RID` is not defined).

**Comment by RFSH** [comment]
There was a bug in `tuple.uniqueId` logic which was causing it to return null in case of alternative tables. I recently changed the ellipses directive to show just `No Value` if the `uniqueId` is null. The combination of these two result in the behavior that you are seeing. I fixed the `uniqueId` bug, the given url is now working as expected.
