### ISSUE TITLE
Token is undefined

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#601]
I consistently get this error message on rbk staging. 

https://staging.rebuildingakidney.org/chaise/recordset/#2/Legacy_RNASeq:File

@robes also came across this on facebase and thought that it is related to markdown to generate thumbnails, but most do not have the urls.
              
@jrchudy @RFSH  Can either one of you check whether this is critical?

**Comment by hongsudt** [comment]
This should be logged on rbk-staging. But I don't see the log message in the console captured from facebase.

**Comment by hongsudt** [comment]
The problem is that the filename and url have newline in it..  Chaise should report this error without breaking. 

S-1GBP | E12_SHHCRE-22G_genes.fpkm_tracking.txt\r                                        +| /gudmap-files/21776/processed/E12_SHHCRE-22G_genes.fpkm_tracking.txt\r                                       
 +

**Comment by RFSH** [comment]
As you pointed out the problem is that markdown-it renderer that we are using is throwing error. The assumption was that this function would never throw an error since there's no invalid markdown string. This is actually a correct assumption with `markdown-it` or any other markdown interpreters. But here, `markdown-it-attrs` extension that we have added to `markdown-it` is throwing error.
For example `[test](/test/\r/a)` returns `[test](/test/<br>/a)`, but `[test](/test/\r/a){.download}` throws the error.

To solve this, we just need to wrap the render function in a try-catch. We need to decide whether we should return the raw value in this case, or just empty string.

**Comment by RFSH** [comment]
Since it required a very simple change, I pushed [the change](https://github.com/informatics-isi-edu/ermrestjs/commit/71b676386895d8544e6dea11dac50e7e67e70af2) to master without creating a PR.
