### ISSUE TITLE
Allow pseudo columns in templating environments

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#617]
You don't need to follow the conversation below and this comment will summarize the list of tasks that we agreed on. You can refer to [this wiki page](https://github.com/informatics-isi-edu/ermrestjs/wiki/Pseudo-Column-in-Templating-Enviornments) that is explaining this change in depth.

- [x] Allow data-modelers to define a set of source keys for each table.
- [x] Allow `sourcekey` in `visible-columns` and `visible-foreignkeys`.
- [x] Add a new `wait_for` attribute in the `display` settings of pseudo-columns.
  - [x] in visible-columns for `compact` context.
  - [x] in visible-columns for `detailed`context.
  - [x] in visible-foreign-keys annotation.
  - [x] in citation annotation.
- [x] Allow pseudo-columns without any `source` or `sourcekey` (markdown_name and markdown_pattern are required in this case).

<details>
<summary>Old description</summary>
Along with introducing pseudo columns in the visible column list, it would be very helpful to have some new annotation mechanism where a pseudo column definition could be injected into the mustache (or handlebars) template environment (without adding it to the rendered visible columns).

We should think this over a bit before diving in.  One question is whether such a mechanism should be additive to the current environment or instead override the default.  An override behavior could be better for future performance, so we don't have to prepare all kinds of raw and rendered data "just in case" the DBA wants to reference it in a template. Instead, they would have a way to declare their data dependencies and we only need to prepare content actually needed by their templates.

The pseudo column mechanism is also more general than the previous foreign key based content, so that feature would seem largely redundant once this is available...

@hongsudt @robes @ljpearlman @bugacov  @mikedarcy 
</details>

**Comment by karlcz** [comment]
@RFSH @hongsudt @robes 

There is an open PR to add handlebars and support a field like `"template_engine": "handlebars"` as a sibling to our many template pattern fields to switch the engine from mustache to handlebars.  I propose that we introduce a similar field `"template_environment": {...}` with new syntax for the DBA to structure the environment explicitly.

We know we want a syntax that can reuse the "source" path notation for facets and pseudo-columns to request linked material for a template.  Ideally, we should be able to express the current default environment using whatever syntax we come up with. That way, in the absence of a DBA configured environment, ermrestjs could generate the default description and then interpret that to produce the backwards-compatible environment using the new common code path.  However, we also want the new syntax to be concise enough for practical use by DBAs and so if these goals are in conflict, I think it is more important to make the new syntax usable so it covers all desired uses cases, even if it is difficult or impossible to exactly replicate the old environment.

## Sketch 1 for Discussion
Assumption: you only need a flat key-value map for the environment, with some rich way of expressing the values that get injected.  We can give the DBA full control for naming the data sources injected into the environment.
```
{
   "key1": { "source": [sourcepath], "entity": boolean },
   ...
}
```
Imagine this produces a template environment with a rich object under `key1` that has two sub-fields:
- `key1.raw`: Raw column value (for scalar sources) or nested object (for entity sources)
- `key1.display`: Display column value or display name of entity

Benefits: explicit w/o surprises and sidesteps issues like how to mangle or encode column names with whitespace or other punctuation that looks like template meta-syntax.

Drawbacks: this could get very verbose to build an environment including lots of columns and foreign keys. Also, I don't think you can exactly replicate the current behavior for `$fkeys` or `$moment` without some other kind of magic syntax.

## Sketch 2 for Discussion
Assumption: we want to make the syntax more concise for complex cases.

Instead of having a flat environment-source mapping as above, have sections with instructions specific to special cases:
```
{
   "columns": [ column, ... ],
   "fkeys": [  [ schema, constraint ], ... ],
   "sources": [
      {"source": [ sourcepath1 ], "entity": boolean, "key": "key1"},
      ...
   ]
}
```
- `"columns"` map implicitly to keys `cname` and `_cname` w/ name mangling as now
   - if field is boolean `true` instead of list, implement backwards-compatible set of columns
- `"fkeys"` map implicitly into the `$fkeys` hashmap as now
   - if field is boolean `true` instead of list, implement backwards-compatible set of all fkeys
- `"sources"` map into a new `$sources` hashmap keyed by the `"key"` field in each source?
   - for each `key` holding formatted value, also imply `_key` with raw value?

Benefits: more backwards-compatibility and lazy transitional usage where you combine existing implicitly injected columns and fkeys with a small number of pseudo-column sources.  Less boilerplate to enumerate a number of columns or outbound fkeys since you avoid the outer source-wrapping syntax.

Drawbacks: redundant ways to express the same thing, perpetuates the name-mangling environment structure hacks, and allows expression of colliding keys for multiple sources.

**Comment by hongsudt** [comment]
@ljpearlman I would like your opinions on this as well..

**Comment by ljpearlman** [comment]
I'm not sure I understand the two alternatives here, but I am very, very, very strongly in favor of having the DBA specify what data they need in advance instead of having everything fetched just in case. In general I find myself wanting to go less "wide" (not bring in every linked table) and more "deep" (traverse two layers of foreign key) than the current implementation allows.

**Comment by ljpearlman** [comment]
I'm not sure this is the right place to put all this, but here are some related use cases. I think the first two are covered by both alternatives listed above, but I'm not sure about the third.

1. We have many foreign keys that don't get used at all in recordset displays; pre-fetching all of them slows performance a lot (this is related to ermrest:193).

2. We have many cases where we want to link to related records for tables that are related by a relatively long series of inbound and outbound foreign keys. For example, in GUDMAP, the Specimen table has an inbound fk from an association table called Specimen_Probe, which has an outbound fk to the Probe table, which has an outbound fk to the Gene table. We want to see related genes on the Specimen table, so we currently have a table called Specimen_Gene_Association that we maintain with a series of triggers, and we show this as an inline table on the Specimen page.

3. We have some cases where we would like to do the equivalent of removing the one-hop limitation from row_markdown_pattern. For example, we have a table called Specimen that has outbound foreign keys to other vocabulary-type tables (species, developmental stage, etc.). We'd like the row display for the Specimen table to reference columns (i.e., the name for each of these things) from those vocab-like tables. Technically, we can do this, and it will show up in the title of each Specimen record page, but we'd also like Specimen links to show up that way in tables that reference the Specimen table.
Currently, we're cheating a bit by using names as our foreign keys in vocabulary-like tables, but as we move to the more standardized vocabulary format, this will become more of an issue, as we'll need to link to dbxrefs instead of names (names in the new model are not, by themselves, unique; what's unique is the combination of name, controlled vocabulary, and "obsolete" status; we'll probably end up with only one non-obsolete term for each name in each domain table, but we may have obsolete and non-obsolete terms with the same name).

If you could show how these two cases could be expressed in each of the alternatives you listed above, that would help me understand the differences:

1. Given the tables:
Specimen <- Specimen_Probe -> Probe -> Gene (resulting in a many-to-many Specimen<->Gene mapping), how would we show Genes in the Specimen table display?

2. Given the tables:
(Many tables) -> Specimen -> Developmental_Stage, how would we annotate the Specimen table so that the Developmental Stage.Name column shows up as part of the display for the Specimen link in the tables that link to it?

**Comment by karlcz** [comment]
@ljpearlman I actually think both of your scenarios above are mostly orthogonal to this topic and will need other enhancements to make them practical.

The new pseudo column aggregates feature allows you to include an array of scalars from the Gene table per Specimen in the recordset results. Shortly, I expect it will also support an array of Gene row-names, i.e. supporting `entity: true` pseudo column array aggregates. However, it currently renders the array as a comma-separated list of members and does not allow you to customize it with a markdown pattern on that pseudo column.  It seems to me we should be able to add a way for the DBA to supply such a markdown pattern as some new fields in the pseudo column definition and/or some new context key for the existing table and column display annotation.

Unfortunately, we don't have composition to allow a row-name presentation on Specimen to use external values and somehow turn that into a different pseudo column for each of your many referencing tables. In practice, I think you'll still have to denormalize development stages into your specimens if you want to render them that way.  FWIW, there is a hack you can do with an overlapping composite foreign key from Specimen to Development_Stage to denormalize this content w/o any triggers.

**Comment by karlcz** [comment]
This was a long time ago, but I think the reasoning in the second sketch was to stick with the mustache-friendly environment hack, so each source gets stored into two separate environment fields `key` and `_key` just like the columns are currently mapped.

The other sketch assumes we will discard that old convention and use sub-fields to access raw vs display values.  I think we could also define a hybrid of the first sketch to allow _some_ of the brevity, by allowing different syntactic short cuts?

    {
      "source1": {"source": ...},
      "Column1": true,
      "Column2": "Column 2",
      "fkey1": ["Schema", "Constraint1"],
      ...
    }

- The `{"source"...}` syntax is of course the fully general scenario with arbitrarily assigned environment key.
- The `true` (or `1`?) syntax avoids repeating a column name if it can be used exactly as environment key.
- The `"Column 2"` syntax allows arbitrary column names where the DBA must provide a mangled environment key since we won't automatically assign environment keys anymore nor do name mangling.
- The `["Schema", "Constraint1"]` syntax allows the simple foreign key shorthand but with DBA assigned environment key.

**Comment by karlcz** [comment]
If we are going to go forward with handlbars and hopefully deprecate mustache, I lean towards also moving towards this sort of explicit control and deprecating our old environment construction rather than keeping it around as some perpetual backwards-compatibility mode...

**Comment by robes** [comment]
In principle, that sounds good to me. But what is the impact on deployments. If backward compat is dropped, will the effort (to update existing annotations) be so great that we will have some deployments lag behind. Etc. Perhaps one way to avoid that situation is to provide an upgrade script written in deriva-py that walks the model and updates all older annotations to the new format.

**Comment by hongsudt** [comment]
```
tag:isrd.isi.edu,2018:env-variables:
{
   "columns": [col1, col2],
   "fkeys": [  [ schema, constraint ], ... ],
   "sources": [
      {"source": [ sourcepath1 ], "entity": boolean, "key": "key1"},
      ...
   ]
}

"tag:isrd.isi.edu,2016:visible-columns": {
  "detailed": [
      {
        "source": ["key1","key2"],
        "display": {
          "markdown_pattern": "<prefix> {{{$pcol.key2}}} <suffix>",
          "template_engine": "handlebars",
          "page_size": "",
           "row_order": ""
           "aggregate-column": true
        }
      }
   ]
}

```

**Comment by RFSH** [comment]
@hongsudt @karlcz

When we designed this we were mainly focused on the source syntax. Which means that we are now going to be able to access pseudo-column in templates that are directly defined in the source syntax (in `visible-columns` and `visible-foreign-keys` annotations).  

Since some of the pseudo-column data might not be available on load, we needed a way to signal chaise/ermrestjs when we have the data and therefore should process the given template. For that, we've added `waitfor` which is a flat list of dependencies. 

Now we need to evaluate this design. To see if it make sense to be able to access pseudo-columns in templates that are defined for other annotations (which ultimately means whether it makes sense to add `waitfor` to these annotations or not).The following are the different annotations that are utilizing templating.

#### 1. [Citation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2018-citation)

```javascript
"tag:isrd.isi.edu,2016:foreign-key": {
  "journal_pattern": "",
  "author_pattern": "",
  "title_pattern": ""
  "year_pattern": "",
  "url_pattern": "",
  "id_pattern": "",
  "template_engine": "",
  "waitfor": [] // ?
}
```

This annotation is used for generating the citation dialog that we are showing after clicking on "share" button in record page. Supporting pseudo-columns in this annotation is actually [one of the requested features](https://github.com/informatics-isi-edu/chaise/issues/1750).

From ermrestjs/chaise stand point, adding this should be relatively simple. The only issue here would be the UX. If a citation definition relies on an aggregate, we should either hide the share button or disable it, until we have the aggregate data.

#### 2. [Column display](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-column-display)

```javascript
"tag:isrd.isi.edu,2016:column-display": {
  "context": {
    "pre_format": "",
    "column_order": [],
    "markdown_pattern": "",
    "template_engine": "",
    "waitfor": [] // does this make sense?
  }
}
```

#### 3. [Key display](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2017-key-display)

If you use a key constraint definition in your visible-columns, we are going to show a self-link to that row. Using this annotation, you can change this heuristic.

```javascript
"tag:isrd.isi.edu,2016:key-display": {
  "context": {
    "column_order": [],
    "markdown_pattern": "",
    "template_engine": "",
     "waitfor": [] // does this make sense?
  }
}
```

#### 4. [Table display](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-table-display)

This annotation is used for two purposes (based on different context):

- row-name: The row-name is heavily used in different contexts. For example the heuristics for showing a ForeignKey Pseudo-column, is using the table's row-name. So this annotation is used outside the main table that this is defined for. Therefore the `waitfor` definition might be confusing.

```javascript
"tag:isrd.isi.edu,2016:table-display": {
  "row_name": {
    "row_markdown_pattern": "",
    "template_engine": "",
    "waitfor": [] // ?
  }
}
```

- markdown display of inline/related tables in record page. This has the same issue as the other use case. Assuming `M` is the name of the main table and `R` is the related table. When we're showing table `R` in the related/inline section, we're using the table-display that is defined on table `R` to generate the markdown display for us. Since this is done in context of table `M`, the active list is based on `M` but the annotation is defined on table `R` and therefore it doesn't make sense for its `waitfor` to use the active list of `M`.

```javascript
"tag:isrd.isi.edu,2016:table-display": {
  "compact": {
    "row_order": [],
    "page_size": 25,
    "hide_column_headers": false,
    "collapse_toc_panel": false,
    "separator_markdown": "",
    "prefix_markdown": "",
    "suffix_markdown": "",
    "row_markdown_pattern": "",
    "page_markdown_pattern": "",
    "template_engine": "",
    "waitfor": [] // which active list? M? R?
  }
}
```

Compare this to the case of defining the `markdown_pattern` and `waitfor` directly in the `visible-foreign-keys` definition, which is in context of `M` and it makes sense that the waitfor is written based on active list of `M`.

```javascript
"M": {
  "annotations": {
    "tag:isrd.isi.edu,2019:source_definitions": {
      "sources": {
        "key1": {// some definition }
      },
      "tag:isrd.isi.edu,2016:visible-foreign-keys": {
        "detailed": [
          {
             "source": [// path to the related table R ],
             "display": {
               "markdown_pattern": "",
               "template_engine": ""
             },
            "waitfor": ["key1"] // based on M's source definitions and not Rs
           }
        ]
      }
    }
  }
},
"A": {
  "annotations": {
    "tag:isrd.isi.edu,2016:table-display": {
      "*": {
        "row_markdown_pattern": "" // has access to A data and not M
      }
    }
  }
}
```

#### 5. [Asset url pattern](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2017-asset)

```javascript
"tag:isrd.isi.edu,2017:asset" : {
  "browser_upload": false,
  "filename_column": "",
  "byte_count_column": "",
  "md5": "",
  "sha256": "",
  "sha256": "",
  "filename_ext_filter": [],
  "url_pattern": "",
  "template_engine": "",
  "waitfor": [] // ?
}
```
Currently in the `url_pattern` you cannot even access the `$fkeys`. The main problem is that we are generating `url_pattern` in create mode based on the row data. Therefore the data for the tables that have relationship to the given row are still unspecified. I'm not sure how this can even work.

#### 6. [Foreignkey domain filter pattern](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-foreign-key)

```javascript
"tag:isrd.isi.edu,2016:foreign-key": {
  "from_name": "",
  "to_name": "",
   "display": {
    "context": {
      "column_order": []
    }
   },
  "domain_filter_pattern": "",
  "template_engine": "",
  "waitfor": [] // ?
}
```

This has the same issue as asset's url_pattern. Since this is used in create mode too, the data for the tables that have relationship to the given row are still unspecified. I'm not sure how this can even work.

**Comment by RFSH** [comment]
We had a discussion about this. The following are summary of what we agreed on.

Citation:
- Should be implemented.
- _UX should be discussed_.

Column Display, Key Display:
- Should be implemented.

Table Display:

- We should be able to allow `wait_for` in this annotation.
- What the data-modelers will define in this list are sources that are defined for the current table and not the parent table. Therefore it won't be possible to allow them to access the active-list of main table. 
- We can change the syntax of `wait_for` to allow access to the parent, but that has its own issues as it will make the syntax very difficult to understand. Therefore we decided to not take this approach.
- We should also continue allowing them access to the parent's main entity data in the `page_markdown_pattern`.

Asset url pattern, Foreign key domain filter pattern:
- These annotations are used in entry contexts where the data might not be available.
- There's a current usecase that we want to use an all-outbound path in the asset `url_pattern`.
- With each user input we should send request for any active-list element that has a path (even the outbounds). To mitigate this issue, we should change how we're processing the `wait_for` list. The input columns (normal column or foreign key column) that will change the computed value of this template must be listed in the `wait_for` list. Then we will use the `wait_for` list to figure out which requests we have to send.
- Currently recordedit doesn't have any flow-control which we have to add.

**Comment by RFSH** [comment]
The first implementation of this feature has been added: [ermrestjs PR](https://github.com/informatics-isi-edu/ermrestjs/pull/797) / [chaise PR](https://github.com/informatics-isi-edu/chaise/pull/1796).

We should be able to use pseudo-columns in the `display` setting for pseudo-columns in `compact` context.

The next steps are:
  - [ ] Supporting `wait_for` in visible-column and visible-foreign-keys in detailed.
  - [ ] Supporting `wait_for` in citation annotation.
  - [ ] Supporting `wait_for` in column-display and key-display.

**Comment by RFSH** [comment]
When we were talking about this feature we didn't mention how this would be useful in faceting. We recently came up with a use case for this.

In [this table](https://dev.rebuildingakidney.org/chaise/recordset/#2/Common:Publication@sort(Year::desc::,Month::desc::,RID::desc::)) we currently are showing a facet for `Gene_Expression:Marker_Gene_Publication` table, but the RID is not very useful to the users. What they would prefer to see is the combination of the following values:

- Gene ID: Which comes from `Common:Gene` table that the `Marker_Gene_Publcation` table has foreign key to.
- Anatomy ID: Which comes from `Vocabulary:Anatomy` table that the `Marker_Gene_Publcation` table has foreign key to.
- Stage: Which comes from `Vocabulary:Developmental_Stage` table that the `Marker_Gene_Publcation` table has foreign key to.


There are two different solutions for this:

1. Modifying the row-name to be based on these three values. And since we're showing the row-name in the facet panel that should solve the issue. This means that data-modelers should be able to use the foreignkeys in the `table-display` annotation, or should be able to define their own list of `wait_for`. The only issue here would be the paths that might have inbound direction in them.

2. Allow `display` setting in the facet definition. This means that they should be able to define `wait_for` as well. This would give more flexibility compared to the other solution, but it still has the same issue of dealing with inbound paths.

**Comment by RFSH** [comment]
After discussing briefly about this, we think that we should start supporting pseudo-columns without any source definition. In this case we might want to check for `markdown_name` and `markdown_pattern`,  and invalidate the pseudo-column definition if these two are missing.

**Comment by RFSH** [comment]
While we were discussing about `wait_for`, we didn't specify which types of source definitions are allowed in it. So technically you can have the same entity set that is visible in the record page (either inline or related) as part of the `wait_for` of other columns. But the visible entity sets are currently displayed as tables and the user can interact with them (change the page, page size, or sort). Because of this, we had a discussion about whether we should even allow these types of source definitions in the `wait_for`.

We have three options of dealing with entity sets in `wait_for` definition:

- Upgrade them to `array_d` aggregate.
- Ignore them.
- Use them as-is. Which means sending entity set requests for them. 

The first option is not feasible and can be bad for performance. So in the following, I will summarize how the other two options compare:

-If we go with "as-is" option, we should send different requests for the entity sets that are in `wait_for` and the ones that are visible. As I mentioned in the previous paragraph users can interact with visible entity sets and if we send one request this means that we should keep them in sync. But keeping them in sync is confusing, so we're treating them differently. This can hurt the performance and also requires extra logic in the code.

- If we ignore them, it is different from how we're treating them in the `visible-columns` itself. It might be confusing to allow them in the context, but not as part of `wait_for` in that context.

- With "as-is", since we're going to send entity request, you can also access the foreign key data as well. Although this could hurt the performance when the table has too many outbound foreign keys.

Therefore, it makes sense to eventually go with the third option if we find use cases for it. As a starting step, we can just ignore these types of sources from the `wait_for` completely.

**Comment by RFSH** [comment]
After making changes to the code I realized supporting entity sets should not be an issue and we decided to include it in the next implementation.
We also had a discussion about the priority of requests that we're sending in the record page. The request for getting the main columns and all-outbound is done prior to any other requests, so it's not part of our priority discussion and assumption is that this request has to be done before anything else. Currently, in record page, we have a bucket list of requests. We first send the request for all the inline tables, and then all the aggregates. We're going to remove that. 

For the main part of the page, the requests will be sent from top to bottom depending on the type of the column and what's in the `wait_for`.  

1. First, we're going to traverse the list of `visible-columns` from top to bottom and if the column is inline without any `wait_for`, or has only entity sets as part of its `wait_for`; we're going to send the requests for them (and their `wait_for` list definition).
2. Secondly, we're going to traverse the list of `visible-columns` and if the column is aggregate, or has aggregate in its `wait_for`; we're going to send the requests for them (and their `wait_for` list definition).

To demonstrate this, assume that the following is the visible-columns definition (columns named `es` are entity sets and `agg` are aggregates):

```
i1 (wait_for: agg1, agg2)
i2 (wait_for: es1, es3, agg1, agg3)
i3 (wait_for: es1, es2)
agg4
es4
```

Then the following will be the order of sending requests:

```
(i3, es1, es2), (es4), (i1, agg1, agg2), (i2, es3, agg3), (es4) 
```

For the related section, since we're showing the tables from top to bottom, we should send the requests top to bottom as well (regardless of their types), so in that example this will be the order of requests:

```
(i1, agg1, agg2), (i2, es1, es3, agg3), (i3, ess), es4
```

**Comment by RFSH** [comment]
We have a discussion about supporting `wait_for` on column and key display and decided not to add it to those annotations. For the reasons stated below:

- Allowing data-modelers to define `wait_for` in these annotations doesn't reduce the amount of work that they need to do. They can achieve the same thing by just defining the `markdown_pattern` and `wait_for` in the source definition that is used in the visible-columns annotation.

- The column display is used to generate the value of all-outbound scalar columns. So assume that we're getting the data for table `S:M`, and this is what you have in your visible-columns annotation:

```javascript
"compact": [
  {"source": [{"outbound": ["s", "fk_from_M_to_F1"]}, "col"]}
]
```

Then to get the value of this pseudo-column, we're going to use the column-display of `col` column in the `F1` table. Now if we allow data-modelers to define a `wait_for` in this column-display, the `wait_for` is defined based on `F1` table; but in this case, we want to use it in the context of table `M`. The `wait_for` might be using multiple sources defined on `F1`. So if we actually want to support this, we have to add the path from `M` to `F1` to all the sources defined in the active list of `F1`. This can be incorrect and might extra issues as there might be a loop in the produced path. Therefore we shouldn't try to this this.

**Comment by RFSH** [comment]
The further part of the changes that are described in this issue have been merged with master. This includes 

- Addition of `VirtualColumn`s
- Allowing `wait_for` in `detailed` context of `visible-columns` and `visible-foreign-keys`
- Allowing `wait_for` in `citation` annotation.

**Comment by RFSH** [comment]
In a recent annotation change that @bugacov is working on for facebase, he mentioned a use case that could benefit from supporting aggregates in table-display annotation. 

<details>
<summary>Click here for more information about the issue</summary>

### Desired behavior
To simplify the explanation, let's assume that we're focused on table A on the record page. This table has a many-to-many relationship to table B. And table B has a many-to-many relationship to table C. We're showing table B in the related table section. Now in the custom-display mode, for each row in table B, we want to show the applicable rows in table C. Something like the following:

```
Title: Table B row 1
Available Cs: C1 C2

Title: Table B row 2
Available Cs: C3

Title: Table B row 3
Available Cs: C1 C3 C4 C7

```

### Current solution
Since all the aggregates that are written for the record page are starting from table A, we cannot simply write an aggregate definition that goes from A to C. That would give us the same result for the listed Available Cs. Therefore, in the current solution, we're also adding a condition to make sure applicable rows are displayed, so something like:

```javascript
"source-definitions": {
  "sources": {
    "aggregate-col": {
      "source": [], // path from A to C
      "entity": true,
      "aggregate": "array_d"
    }
  }
},
"visible-fks": {
  "source": [..], // path from A to B
  "markdown_pattern": "{{#each $self}}Title: {{this.Title}}\n Available Cs: {{#each ../aggregate-col}}{{#if (eq this.values.some_col_in_c ../values.som_col_in_B) }}{{this.values.C_Name}}{{/if}}{{/each}}\n{{/each}}"
},


```
(so two loops inside each other with an `if` condition)

This solution works but is not ideal,

- We have to filter on the client-side and it only works in this case. In this case, we know that the number of rows is small, and also because of the model structure, there's a column that we can filter based on. This might not be available in other models.
- Because of the `if` condition, we cannot easily show a comma in between the results (we don't know which one is the last, so we cannot conditionally hide the added comma after the last element.)

### Better solution

The better solution would be having aggregates in table-display annotation. This way, we could write table-display annotation for table B that has aggregates that start from table B. Then we can simply just loop through the result without any additional condition. 

</details>
