### ISSUE TITLE
Wrong tooltip on entity-mode pseudo columns

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#623]
When a pseudo column is in entity mode, the tooltip should come from the table's comment rather than the key column's comment.

I also suspect we should add support for a "comment" field in the pseudo column (sibling to "markdown_name") so that a DBA can customize the tooltip to better express the meaning of the whole source path.

**Comment by RFSH** [comment]
Based on the discussion that we had the following should be the logic for both displayname and comment of pseudo columns (first rule applicable).


### Displayname
1. Use the defined `markdown_name`.
2. If aggregate is defined, use the following:
    - min: `Min {COL_NAME}`
    - max: `Max {COL_NAME}`
    - cnt/cnt_d: `# {COL_NAME}`
3. If there's no path (column from same table)
   - If `entity` mode: It's the same as `KeyPseudoColumn`, and therefore it should have the same logic.
  - Otherwise return column's displayname.
4. If it's inbound foreign key (pure and binary, or just a single inbound fk), use the same logic as `InboundForeignKeyPseudoColumn`.
5. Otherwise return the end table's displayname.

### Comment
It should align with the displayname, therefore:
1. Use the defined `comment`.
2. If aggregate is defined, use the following:
    - min: `Minimum of {COL_NAME}`
    - max: `Maximum of {COL_NAME}`
    - cnt: `Number of {COL_NAME}`
    - cnt_d: `Number of distinct {COL_NAME}`
3. If there's no path (column from same table)
   - If `entity` mode: It's the same as `KeyPseudoColumn`, and therefore it should have the same logic.
  - Otherwise return column's comment.
4. If it's inbound foreign key (pure and binary, or just a single inbound fk), use the same logic as `InboundForeignKeyPseudoColumn` (comment of fk, or comment of association table).
5. Otherwise return the end table's comment.

**Comment by RFSH** [comment]
This has been done as part of #626. Both displayname and comment have been changed based on the logic described on the previous comment.
