### ISSUE TITLE
Revise DataPath filter interface

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#66]
Right now `DataPath.filter(...) => DataPath` returns a new instance of the DataPath, so while we naturally think about and explain ERMrest data path expressions like this:

```
A/B/<filter>/C/<filter>...
```

The API forces us to put all the filters at the end. We **cannot** do this:

```
var dp = DataPath(ATable).extend(BTable).filter(...).extend(CTable).filter(...);
```

Instead, we have to do this:

```
var dp = DataPath(ATable).extend(BTable).extend(CTable);
var filtered_dp = dp.filter(...); /* apply all filters for B and C here */
```

I think even in our limited experience with our team so far, almost everyone finds this non-intuitive. I suggest we rethink this.
### Revised interface

Discussing this with @karlcz, have a few ideas on how we might make this interface better overall. First see #70 which discusses moving the access interfaces to the path table instance. This proposed change would then move the filters to the access methods themselves.

```
PathTable
  .entity /* access interface object */

Entity
  .get(filter) /* get entities filtered by 'filter' param */
```
### Example usage:

```
var dp = DataPath(A);
var a = dp.root;
a.join(...);

var filter = /* according to filter api as currently defined, though subject to change */

var promise = a.entity.get(filter);
```

This makes it clear that `filter` does not mutate the datapath `dp` instance.

**Comment by hongsudt** [comment]
@robes @karlcz I am putting this in backlog since both of you want to rethink this api over, correct?

**Comment by robes** [comment]
Sure, we need to review the whole DataPath api early next week, I believe.

**Comment by robes** [comment]
I think this is going to get resolved in the course of #65

**Comment by jrchudy** [comment]
"I think even in our limited experience with our team so far, almost everyone finds this non-intuitive."

I can confirm that I tried to use it by calling the following `.filter(...).extend(...).filter(...)` and not understanding why it wouldn't work.

**Comment by karlcz** [comment]
I think it's fine to change to a mutating behavior for join() and filter() as long as we have a copy() method that can be used to support copy-write branching of one path for apps like search and details that need to drill down into various sub-trees from the same base path.

The original API sketch was aiming for a copy-on-write idiom but it's more or less equivalent to a copy-before-write idiom if you prefer stateful OOP to functional programming style.  Either can support chaining, but you need to remember to capture the result of such a chain when using a functional style, rather than expecting it to be captured as mutation of an existing object...

In either case, it is much easier to capture snapshots into variables and use them later than to try to get back to the previous state through "inverse" mutations. I intentionally omitted any such inverse methods for this reason. I.e. there is no "unjoin" or "unfilter".

**Comment by robes** [comment]
@karlcz I'm fine with that approach too.

Let's see, so we could put the `.filter(...)` on the `PathTable` (or the DataPath but PathTable might be more intuitive). If the filter function returns _this_, then the chaining can be quite natural. If its going to be mutating, then it could implicitly form a conjunction between calls to filter.

```
PathTable
 .join(joinspec) -> returns new PathTable instance based on joinspec
 .filter(filterspec) -> returns 'this'
 ...
```

Usage:

```
var path = DataPath(A);
var a = path.root;
a.filter(filterspec).join(B); /* adds filters, which returns 'a' again, then joins B on a returning b */
...
a.join(C).filter(morefilters).join(D); /* joins C, which returns pathtable c, adds more filters, joins D */
```

I don't think that our `fitlerspec` has to be scoped to the current PathTable instance although one might naturally think of it that way. In other words, the filters could include columns from a different PathTable. That way you could just save up all your filters and apply them at the very end.

```
a.join(B).join(C).join(D).filter(<a filter with predicates from a, b, c, d in it>);
```

And then we can make a public `DataPath.copy()` function. (We currently have a private `_copy()` function that can be revised for this purpose.)

**Comment by robes** [comment]
Since faceting has been implemented without need for this issue, we should close this unless some other use case requires that we revisit it.
