### ISSUE TITLE
Need to support access to viewer app link with proper version 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#673]
Currently, the URL to the viewer app is put together manually.. We want to avoid this so that version can be automatically inserted by ermrestjs..  I guess a different approach is to provide $chaise.versionedCatalog that markdown it can used in the template..  Maybe the later approach is more generic. 

@karlcz what do you think? 

Here is the current annotation that we use to direct users to the viewer app..  

"markdown_pattern" : `"{{#uri}}::: iframe [{{{Name}}} (full screen)](/chaise/viewer/#2/Immunofluorescence:Slide/id={{#encode}}{{id}}{{/encode}}?waterMark={{#encode}}{{$fkeys.Immunofluorescence.Slide_Consortium_fkey.values.URL}}{{/encode}}){width=1024 height=600 resize=both link=/chaise/viewer/#2/Immunofluorescence:Slide/id={{#encode}}{{id}}{{/encode}}?waterMark={{#encode}}{{$fkeys.Immunofluorescence.Slide_Consortium_fkey.values.URL}}{{/encode}} } \n:::{{/uri}}"`

**Comment by karlcz** [comment]
Yes, I think you need to expose the versioned catalog ID as a mustache
environment field.

**Comment by carlkesselman** [comment]
Actually don't we want more then that.  We should not be writing annotations with the catalog number hard wired or is the #2 a parameter?

Carl

Sent from my iPhone

On Jul 10, 2018, at 12:11 AM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the URL to the viewer app is put together manually.. We want to avoid this so that version can be automatically inserted by ermrestjs.. I guess a different approach is to provide $chaise.versionedCatalog that markdown it can used in the template.. Maybe the later approach is more generic.

@karlcz<https://github.com/karlcz> what do you think?

Here is the current annotation that we use to direct users to the viewer app..

"markdown_pattern" : "{{#uri}}::: iframe {{{Name}}} (full screen)</chaise/viewer/#2/Immunofluorescence:Slide/id=%7B%7B#encode%7D%7D%7B%7Bid%7D%7D%7B%7B/encode%7D%7D?waterMark=%7B%7B#encode%7D%7D%7B%7B$fkeys.Immunofluorescence.Slide_Consortium_fkey.values.URL%7D%7D%7B%7B/encode%7D%7D>{width=1024 height=600 resize=both link=/chaise/viewer/#2<https://github.com/informatics-isi-edu/ermrestjs/pull/2>/Immunofluorescence:Slide/id={{#encode}}{{id}}{{/encode}}?waterMark={{#encode}}{{$fkeys.Immunofluorescence.Slide_Consortium_fkey.values.URL}}{{/encode}} } \n:::{{/uri}}"

**Comment by carlkesselman** [comment]
Ok. Good.  I only know beards not mustach

Car

Sent from my iPhone

On Jul 10, 2018, at 1:02 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

That's the point about the mustache environment. The `2` (or `2@XYZ`
should be replaced with something that expands in the front-end,
e.g. `{{{$chaise.catalog}}}` or `{{{$chaise.versionedCatalog}}}`.


karl

**Comment by RFSH** [comment]
I am going to close this issue since #693 has added the three variables that can be used to get catalog information:
```
$catalog.snapshot
$catalog.id
$catalog.version
```
