### ISSUE TITLE
Add client_string to capture app_name when making a call to ermrest

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#69]
@karlcz @robes Can you specify the detail on how ermrest or chaise needs to change to capture this information in the server log?

**Comment by karlcz** [comment]
ERMrest ignores query parameters in the URL that it does not understand.

So for example we can just add a `cid` parameter, i.e. client ID, and specify whatever we want:

    GET /ermrest/catalog/1/entity/dataset?limit=2&cid=myclient

the raw URL is reported in the default logging on all the servers and so will start being captured immediately.

We may also want to consider a page ID (i.e. a GUID for each page load) to distinguish requests from multiple instances of the app?  However, there may be privacy concerns here so I wouldn't rush to do something like this...

**Comment by karlcz** [comment]
BTW I am suggesting this approach with query parameters to avoid having to roll out server-side changes to all servers to enable other custom logging, such as for a new request header.

**Comment by hongsudt** [comment]
1. change the server api to incorporate cid
2. chaise apps pass the cid to ermrestjs through the new API
3. ermrestjs includes cid into all ermrest calls

Here is the proposed change based on our discussion this morning: 
```
Server
  .new Server(uri, cid="null")  /* when the server is created, set the cid associated with it */
  ._cid
```

Potential cids: 
* record
* record2
* recordedit
* recordset
* viewer

@robes does this make sense?

**Comment by robes** [comment]
@hongsudt I can't help much until I understand _what_ problem you are trying to solve. I can sort of infer the problem from this proposal on _how_ to solve the problem (which I don't fully understand).

Why do you want to log the app named?

**Comment by hongsudt** [comment]
2 goals: 
* so we can do data analytics based on the app  
* it should also help with debugging. Eventually, we want the iobox or other components to start passing this clientid to the server as well.

**Comment by robes** [comment]
My $0.02... I would consider doing analytics using Google or other analytics service instead. And at the same time, have ermrest (apache) start logging the user agent so that you know when a call is from IObox rather than from an AJAX client.

But if you want to do it this way. I suggest tracking:
- app name, and
- session (logical session not authN related)

You will need to push this up a level to the ermrestjs `getServer` function too, in addition to the `Server` constructor. If `cid` is the client ID, then `sid` could be the session ID.

```
getServer(uri, sid=null, cid=null)
...

Server(uri, sid=null, cid=null)
 ._cid
 ._sid
```

Since `getServer` implements a singleton pattern, it might need to be modified to return a single instance of Server not just based on `uri` but on `cid` and maybe `sid` as well.

I would consider having `getServer` generate a new `sid` if the caller passes a null. It can be a UUID. Applications like Chaise could pass their `sid` to each other and reuse it. We would then be able to track calls between apps that are related by a similar logical (user) session.

**Comment by carlkesselman** [comment]
Yes, I wonder why we are not looking at using google analytics for this.  Do we really have to build out our own analytitic tools, log parsers, etc.  I don’t know enough about this, but it seem that using this might be  good enough start.  See: https://developers.google.com/analytics/devguides/collection/analyticsjs/events#examples

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 28, 2016, at 1:42 AM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


My $0.02... I would consider doing analytics using Google or other analytics service instead. And at the same time, have ermrest (apache) start logging the user agent so that you know when a call is from IObox rather than from an AJAX client.

But if you want to do it this way. I suggest tracking:

  *   app name, and
  *   session (logical session not authN related)

You will need to push this up a level to the ermrestjs getServer function too, in addition to the Server constructor. If cid is the client ID, then sid could be the session ID.

getServer(uri, sid=null, cid=null)
...

Server(uri, sid=null, cid=null)
 ._cid
 ._sid


Since getServer implements a singleton pattern, it might need to be modified to return a single instance of Server not just based on uri but on cid and maybe sid as well.

I would consider having getServer generate a new sid if the caller passes a null. It can be a UUID. Applications like Chaise could pass their sid to each other and reuse it. We would then be able to track calls between apps that are related by a similar logical (user) session.

**Comment by karlcz** [comment]
I think you guys are talking about separate things.  Nobody is saying we should not use GA but that serves a different purpose. The goal here is not to do user analytics but to make our logs more useful whenever we are diagnosing problems, etc. If we use GA events they should be for meaningful GUI events you would want to analyze, not for low-level implementation chatter.

As an example, yesterday I found some recurring errors in server logs while investigating another unrelated bug report. I had to guess which client application was sending the requests by trying to recognize the app's fingerprint in terms of a set of correlated requests and even the style of the developer who wrote the code forming the request URLs. We were able to turn this observation into a bug report and bug fix in one afternoon, whereas there were apparently many users (including our own staff) who encountered the GUI error but failed to report it in an actionable way.

We already have a stream of requests coming in from several apps and this stream is getting harder to interpret. The apps are expanding in scope and sharing more code, and soon it won't be so easy to fingerprint an app the way I did yesterday.

As I stated earlier on this issue, I think we only need to try the simplest thing: a short client ID to stamp each request with the front-end app. I think it should be trivial to add this during app startup so that there is no impact on application complexity and negligible  impact on performance of the app or server. If we want to future-proof it, we might think about an optional API feature to allow the app to set different identifiers for significant app sub-systems, again so we can easily infer which client-side code is responsible for which requests.

**Comment by hongsudt** [comment]
@robes @karlcz and I decided that for flexibility, instead of listing all the ids as explicit parameters, we will instead use a json object that contains those ids. As a starting point, only support cid.. 
```
params={"cid":"app name"}
```

**Comment by howdyjessie** [comment]
@robes reminded me we can wrap the `$http` object, which reminded me we can write an interceptor for this, so I'm working on that.

**Comment by robes** [comment]
Just doing some reading on $http and how we could wrap it. I know Josh has also mentioned doing an Interceptor, but my reservation there is it seems like it has to be a more Angular thing and I’m trying to keep Angular out of ermrestjs, as much as possible.

https://docs.angularjs.org/api/ng/service/$http

Noticing that $http is actually a function $http(config) and the .get, .put, etc are just some convenience methods. This actually makes a wrapper easy.

We already pass the $http service to ERMrest via the .configure(...) method. What we can do internally is something like:

```
configure = function(http,...) {
  module._http = function(config) {
    config.url += '&extra=params';
    return http(config);
  }
...
}
```

**Comment by howdyjessie** [comment]
@robes Since ermrestjs uses those convenience methods, I'm going to wrap the convenience methods instead of the whole http service.

I need a way to access the current server instance's `._cid` property in `.configure`, but I'm not sure how to best do that. How do I get the current server instance? Is it an overreach to have a `module._cid`? (Can different servers have different client ids?) 

Side note: I don't understand why, in trying to keep Angular out of ermrestjs as much as possible, it's acceptable to use Angular's $http and $q services but no further. The line seems arbitrary to me.

**Comment by robes** [comment]
Personally, I think we would be better served by passing a header attribute than a variable. Header variables can be added to apache log files easily. It's something like `...%{header}...`. This makes more sense to me than adding query parameters to an ermrest url just because we know they will be ignored, for now.

**Comment by howdyjessie** [comment]
Thanks to @robes, ermrestjs now uses its own wrapped version of the `http` service to add a `cid` to relevant ajax calls. Also: 
- Each instance of the `Server` class gets its own wrapped `_http` service.
- The `Entity` class constructor has a new server parameter (`new Entity(server, table)`).
- Each call that used `module._http...` has been changed to `this._server._http...`.

**Comment by hongsudt** [comment]
@chiragsanghvi can you please help me review this issue?

**Comment by chiragsanghvi** [comment]
@hongsudt  Yes this is working. I tested it on browser.

@howdyjessie For Chaise is `cid`  supposed to be null for now ?

**Comment by howdyjessie** [comment]
@chiragsanghvi Yes for now it's null because the code to add app names to Chaise apps is in a PR.

**Comment by chiragsanghvi** [comment]
@howdyjessie Ok cool, then I will close this issue.
