### ISSUE TITLE
export: add extra columns from outbound fks

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#731]
Change the main entity request to attributegroup and add extra meaningful column values for outbound foreignkeys. For example showing the RID of a foreignkey value might not be useful, and we might be able to replace it with other fields (the same type of heuristics that we have for row-name). See #701

**Comment by RFSH** [comment]
The following are more details about this task:

- We should do this for related entity requests too.
- We should do this for all the foreignkeys regardless of the type of foreignkey (composite vs. simple); as long as the referred table has one of the candidate columns (the same columns that we're using for row-name, i.e. title, name, term, label, accession_id, accession_number). 
- We should not remove the foreign key columns from the request and these are just additional information.
- We should name them in the `<referred-table>.<candidate-column-name>` format.

**Comment by carlkesselman** [comment]
It would be good to coordinate this so that ingest of the exported file works.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jan 16, 2019, at 11:58 AM, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>> wrote:


The following are more details about this task:

  *   We should do this for related entity requests too.
  *   We should do this for all the foreignkeys regardless of the type of foreignkey (composite vs. simple); as long as the referred table has one of the candidate columns (the same columns that we're using for row-name, i.e. title, name, term, label, accession_id, accession_number).
  *   We should not remove the foreign key columns from the request and these are just additional information.
  *   We should name them in the <referred-table>.<candidate-column-name> format.

**Comment by RFSH** [comment]
This has been merged with master. Assigning to @hongsudt for review, and suggest extra changes if needed.

**Comment by RFSH** [comment]
#785 and #786 has been created for further changes regarding this. I am going to close this issue.
