### ISSUE TITLE
Extend pseudo-column to support presence checking

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#737]
This aggregate will be useful if we want to show whether the assay exist instead of counts, and can be used in combination of presence-checking facet..

@karlcz you mentioned that there is an in-expensive way to do this.. Can you put the detail here? 

Otherwise, what we can do is use the count aggregate and if it is more than 0 then it is present.

**Comment by karlcz** [comment]
Chaise is already splicing in recordset pseudo columns as a separate
query for one column of aggregated results for one page of records. It
adds a pseudo column projection to a base query representing the
records in the current page.

The trick here would be to formulate a query which only returns the
subset of those records for which the pseudo column value would be
true. Instead of adding a pseudo column projection with an aggregate
function, translate the pseudo column into an extra path predicate to
filter the results.

When merging the result into the page, Chaise has to consider that the
rows present in the result are a sparse subset, setting their
presentation values to "true" while setting the other excluded rows in
the page to "false".

That should allow the database to look for a plan that detects related
record presence without having to perform the extra work to visit all
related records nor to aggregate them.

**Comment by RFSH** [comment]
@hongsudt 
I'm not sure if this is still needed or not. But with the addition of `markdown_pattern` to the pseudo-column definition, you can use `cnt` aggregate function and manipulate the display to do the presence checking.

````
{
  "source": [{"inbound": ["s", "f2_cons"]}, "f2_id"],
  "aggregate": "cnt",
  "display": {
    "markdown_pattern": "{{#if (eq $_self 0)}}No matching row found.{{else}}At least one matching row found.{{/if}}",
    "template_engine": "handlebars"
  }
}
````

 I'm not sure about performance. Maybe adding a built-in presence-checking aggregate function might be the better option.
