### ISSUE TITLE
Inconsistent Behavior of source and bare column for assets

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#757]
The source syntax is not applying the asset logic appropriately. Having just the bare column name will turn it into an asset column, but using the source syntax is not behaving the same.

This is happening because of a bug in the `_isEntityMode` helper function. It's not handling sources without path correctly. That is eventually causing [this if case](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/column.js#L45) to fail and therefore won't apply the correct asset column logic.

**Comment by RFSH** [comment]
I realized that this is happening because of the specific `KeyPseudoColumn` that we have added before pseudo-columns (it's served as a self-link to the row). In this specific instance that I tested, the asset column was also part of a simple key, and therefore it was treated as a `KeyPseudoColumn` instead of the `AssetPseudoColumn`.

To briefly explain this, you can have the constraint name of a key in your visible-columns and ermrestjs would create a `KeyPseudoColumn` (self-link column) based on it. But you cannot have key constraint name in source syntax, therefore I ended up treating a normal `{"source": "id"}` as `KeyPseudoColumn`. And if you don't want the key pseudo-column you have to mention `"entity": false` (`{"source": "id", "entity": false}`).

To resolve this, we decided to add a new attribute to source syntax. If you want a self-link `keyPseudoColumn`, you have to specifically ask for it in the definition. `{"source": "id"}` will be interpreted as a normal column, and `{"source": "id", "self_link": true}` will be interpreted as self-link.

**Comment by carlkesselman** [comment]
What is the definition of a self link in this context?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Feb 5, 2019, at 5:48 PM, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>> wrote:


I realized that this is happening because of the specific KeyPseudoColumn that we have added before pseudo-columns (it's served as a self-link to the row). In this specific instance that I tested, the asset column was also part of a simple key, and therefore it was treated as a KeyPseudoColumn instead of the AssetPseudoColumn.

To briefly explain this, you can have the constraint name of a key in your visible-columns and ermrestjs would create a KeyPseudoColumn (self-link column) based on it. But you cannot have key constraint name in source syntax, therefore I ended up treating a normal {"source": "id"} as KeyPseudoColumn. And if you don't want the key pseudo-column you have to mention "entity": false ({"source": "id", "entity": false}).

To resolve this, we decided to add a new attribute to source syntax. If you want a self-link keyPseudoColumn, you have to specifically ask for it in the definition. {"source": "id"} will be interpreted as a normal column, and {"source": "id", "self_link": true} will be interpreted as self-link.

**Comment by RFSH** [comment]
@carlkesselman You can see some examples of it in [facebase](https://dev.facebase.org/~ashafaei/chaise/recordset/#1/isa:dataset@sort(accession::desc::)). The first two columns in this table are self-links. 

The caption comes the following options (first applicable rule):
  1.  `markdown_pattern` defined on the [`key-display`](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2017-key-display)
  2. Formatted value of constituent column of the key.

And the link is generated by chaise/ermrestjs. It's a link to record app based on the key that you have defined (In the facebase example, the first column is based on RID and the other one is based on accession).

**Comment by RFSH** [comment]
I pushed the changes for this feature. I also updated the examples in [pseudo column document](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/pseudo-columns.md#visible-column-list) to reflect these changes.
