### ISSUE TITLE
Allow fk columns to not be displayed as links

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#808]
The row name of the fks should still work, but provide a way to suppress a link property.

We also discussed about changing the heuristics to turn off automatic fk links in the compact context, but this needs further discussion as it affects existing deployments.

**Comment by RFSH** [comment]
The following are details based on the discussions that we had about this issue.

1. The option that we are going to add should be context based.

2. We might want to add a global attribute that changes this behavior, so you can define it on schema, table, and foreignkeys.

3. Internally the function that returns the display value for a row is used for these cases:
    - Foreignkey pseudo-column
    - All-outbound pseudo-columns in entity mode
    - Individual value of entity aggregate pseudo-columns

    So the option that we are going to add should be applied to all of these cases. This also means that this option should be available in source syntax.
		
4. We might want to change the default behavior of foreign keys. Instead of always adding the links, we might want to do this only for detailed contexts.


### Proposed Solution

We want to add a new context-based display attribute to schema, table, foreignkeys, and source syntax. To achieve this we can add a new attribute to the following annotations:

- [display annotation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2015-display) that is available for schema and table.
- `display` setting under the [foreignkey annotation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-foreign-key)
- `display` setting in the source syntax.

Since this will be used in multiple places we have to be specific about its name. We can call it `add_foreign_key_link` (or any other specific names **?requires discussion?**). We will use the following priority for computing the value of this attribute:

1. `display` under source syntax.
2. `display` under foreign key annotation
3. display annotation of the table.
4. display annotation of the schema.

If you don't define this attribute for any of the contexts, the following default will be applied:

```javascript
"add_foreign_key_link": {
  "*": false,
  "detailed": true
}
```
(We are only going to add links in the detailed context by default **?requires discussion?**)

The implementation of this attribute will be the same as `show_nulls` display setting which is mixing context and inheritance. Each value defined for a specific context overrides the inherited value for the same context while still deferring to the inherited value for any unspecified contexts. This means that if you define the following in source syntax:

```javascript
// defined in the source syntax
"add_foreign_key_link": {
  "compact":  true
}
```

While having the following on the table

```javascript
//defined for the table
"add_foreign_key_link": {
  "detailed": false
}
```

We are not going to add foreign key links when the foreign key is displayed in detailed context while adding them for compact.

**Comment by RFSH** [comment]
@hongsudt This has been merged with master. I updated the documents to reflect this changes.

- The display annotation changes are explained [here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2015-display).
- Pseudo-column `show_foreign_key_links` is [documented](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/pseudo-columns.md#show_foreign_key_links) here.

Can you please try and verify the changes?

**Comment by RFSH** [comment]
Upon reviewing this we decide to rename `show_foreign_key_links` to `show_foreign_key_link` .

**Comment by RFSH** [comment]
I am going to close this issue due to inactivity. We should create a new issue if new changes are needed.
