### ISSUE TITLE
Mustache vs. handlebars doc

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#817]
We need new documentation to explain the difference between these two, to make it easier for data modelers to transform their old mustache template into handlebars.  The followings are what comes to my mind:

- Different if statement.
- Restriction in the adjacency of opening and closing tags (`[](){{{{test}}}}` vs `[](){ {{{test}}} }`).
- encode syntax

**Comment by jrchudy** [comment]
When debugging an annotation with Serban yesterday, we encountered a mustache that required some refactoring. I thought the following was proper syntax but wasn't working:
`{{#if $fkeys.Gene_Expression.Image_Consortium_fkey}}?waterMark={{#encode values.URL}}{{/encode}}{{/if}}` 

The structure of `$fkeys` includes the following object hierarchy:
```
{
  Gene_Expression: {
    Image_Consortium_fkey: {
      values: {
        URL: "<value>"
        ...
      }
    }
  }
}
```

The above conditional was modified to the following so that it would work without any guessing as to whether it is proper or not:
`{{#if $fkeys.Gene_Expression.Image_Consortium_fkey}}?waterMark={{#encode $fkeys.Gene_Expression.Image_Consortium_fkey.values.URL}}{{/encode}}{{/if}}`

I'm not sure if something similar has been mentioned in other docs, or if I misunderstand the difference from mustache to handlebars.

**Comment by RFSH** [comment]
I added a section to handlebars.md to explain these differences as part of [this commit](https://github.com/informatics-isi-edu/ermrestjs/commit/3e17091ad4328fb934dd8a9aa8c682ccc449664e)
