### ISSUE TITLE
support unicode characters from data

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#863]
There is a case where unicode characters, like micron - µ, need to be displayed in chaise after being fetched as part of the data to be displayed.

Currently each chaise app is being defined with the following meta tag:
```html
<meta charset="utf-8" http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
```

This is supposed to be unicode format, so we need to figure out why ermrestJS doesn't produce that content properly.

A very comprehensive set of relevant information can be found [here](https://www.htmlsymbols.xyz/unicode/U+00B5).

**Comment by karlcz** [comment]
Is this a regression?

I am sure we do a lot of unicode testing for ERMrest and I thought
we had checked this for Chaise as well.

If redoing testing, be sure to check unicode for all sources:

Default display passing a value from DB w/ default display:
- Unicode in a table/col name
- Unicode in a text column
- Unicode in a markdown column
- Unicode in a json/jsonb column

Setting a literal unicode value
- In a markdown_name
- In the static part of mustache/handlebars patterns

Interpolation passing a value from DB via mustache/handlebars patterns:
- Unicode in a text column
- Unicode in a json/jsonb column

**Comment by RFSH** [comment]
@karlcz We do have some test cases in ermrestjs that are testing literal Unicode characters. For example, a table named `uᴉɐɯ` that has a column named `pᴉ`.  So if a column value/name is literally the `µ` character, we will show it properly.

What I think we assumed (or at least I assumed) is that we should also interpret Unicode numbers and properly display their symbols.  As in if you use `\u00B5` as the value of the column, we should show `µ` instead. I'm not even sure if this makes sense, but that's what this issue is about.

**Comment by karlcz** [comment]
You should make sure you are using a real JSON decoder, in which case
any escaped unicode sequence should already be decoded before you
see it.  JSON allows inline unicode and escapes, both meaning the
same value once the document is decoded.  Properly escaped unicode
should not be something you have to decode yourself.

(And if we are seeing any JSON documents with improperly escaped
unicode, we should resolve that at the origin, not by adding
additional non-standard decoding rules...)

**Comment by RFSH** [comment]
I am going to close this issue. This was mainly a result of miss-understanding of what's expected from ermrestjs/chaise.
