### ISSUE TITLE
unit test for ermrestjs error handling

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#96]
Generate unit testing to test error handling in ermrestjs.

**Comment by shinyichen** [comment]
Are the changes on branch errortests? @chiragsanghvi

**Comment by chiragsanghvi** [comment]
@shinyichen Yes they're on errortests branch.

**Comment by shinyichen** [comment]
I noticed a few of the methods didn't get tested, `Entity.getBefore` and `Entity.getAfter`. However, these will be replaced with the new API, so maybe this was intentional.

A couple of the test cases didn't make sense: `schemas.get` (02.schema_error.js) and `tables.get` (03.table_error.js). These are not ermrest calls, they only access what's already in the schema. These tests should be similar to what you are doing with `annotations.get` and expect `NotFoundError`.
https://github.com/informatics-isi-edu/ermrestjs/blob/errortests/test/specs/errors/tests/02.schema_error.js#L19-L23
https://github.com/informatics-isi-edu/ermrestjs/blob/errortests/test/specs/errors/tests/03.table_error.js#L19-L23

A few missing tests for non-ermrest calls with `NotFoundError`: `columns.get`, `keys.get`, `mappings.get`, `foreignkeys.get`. 

Finally, does this issue cover retries for 500 and 503 errors, and special case of `entity.delete` with 404 error?

**Comment by chiragsanghvi** [comment]
@shinyichen There is an HTTP retry test case for 500 error in the sample folder, which I had written initially to document use of the mocking framework `nock`. You can see it [here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/test/specs/sample/tests/02.http_retries.js). I need to push the changes that handle 503 and `entity.delete` with 404 error scenarios in an another branch. I will move the test to error folder and push the changes.

Apart from that the `column.get` and `mapping.get` were almost similar to `annotations.get` so I didn't write them. 

`keys.get` and `foreignkeys.get` are not testable as I can't access the `colset` class directly.

**Comment by chiragsanghvi** [comment]
@shinyichen I have added the [http_retry](https://github.com/informatics-isi-edu/ermrestjs/blob/errortests/test/specs/errors/tests/05.http_retry_error.js) testcase to **errortests** branch.

**Comment by chiragsanghvi** [comment]
Fixed in **PR** #132
